#ifndef __AS_BUG_CHECK__
#define __AS_BUG_CHECK__

#include "AllStat.h"

AS_NAMESPACE_BEGIN()

#if AS_UNDEF_VALUES
#ifdef APC_INDEX_MISMATCH
#undef APC_INDEX_MISMATCH
#endif
#ifdef DEVICE_QUEUE_NOT_BUSY
#undef DEVICE_QUEUE_NOT_BUSY
#endif
#ifdef INVALID_AFFINITY_SET
#undef INVALID_AFFINITY_SET
#endif
#ifdef INVALID_DATA_ACCESS_TRAP
#undef INVALID_DATA_ACCESS_TRAP
#endif
#ifdef INVALID_PROCESS_ATTACH_ATTEMPT
#undef INVALID_PROCESS_ATTACH_ATTEMPT
#endif
#ifdef INVALID_PROCESS_DETACH_ATTEMPT
#undef INVALID_PROCESS_DETACH_ATTEMPT
#endif
#ifdef INVALID_SOFTWARE_INTERRUPT
#undef INVALID_SOFTWARE_INTERRUPT
#endif
#ifdef IRQL_NOT_DISPATCH_LEVEL
#undef IRQL_NOT_DISPATCH_LEVEL
#endif
#ifdef IRQL_NOT_GREATER_OR_EQUAL
#undef IRQL_NOT_GREATER_OR_EQUAL
#endif
#ifdef IRQL_NOT_LESS_OR_EQUAL
#undef IRQL_NOT_LESS_OR_EQUAL
#endif
#ifdef NO_EXCEPTION_HANDLING_SUPPORT
#undef NO_EXCEPTION_HANDLING_SUPPORT
#endif
#ifdef MAXIMUM_WAIT_OBJECTS_EXCEEDED
#undef MAXIMUM_WAIT_OBJECTS_EXCEEDED
#endif
#ifdef MUTEX_LEVEL_NUMBER_VIOLATION
#undef MUTEX_LEVEL_NUMBER_VIOLATION
#endif
#ifdef NO_USER_MODE_CONTEXT
#undef NO_USER_MODE_CONTEXT
#endif
#ifdef SPIN_LOCK_ALREADY_OWNED
#undef SPIN_LOCK_ALREADY_OWNED
#endif
#ifdef SPIN_LOCK_NOT_OWNED
#undef SPIN_LOCK_NOT_OWNED
#endif
#ifdef THREAD_NOT_MUTEX_OWNER
#undef THREAD_NOT_MUTEX_OWNER
#endif
#ifdef TRAP_CAUSE_UNKNOWN
#undef TRAP_CAUSE_UNKNOWN
#endif
#ifdef EMPTY_THREAD_REAPER_LIST
#undef EMPTY_THREAD_REAPER_LIST
#endif
#ifdef CREATE_DELETE_LOCK_NOT_LOCKED
#undef CREATE_DELETE_LOCK_NOT_LOCKED
#endif
#ifdef LAST_CHANCE_CALLED_FROM_KMODE
#undef LAST_CHANCE_CALLED_FROM_KMODE
#endif
#ifdef CID_HANDLE_CREATION
#undef CID_HANDLE_CREATION
#endif
#ifdef CID_HANDLE_DELETION
#undef CID_HANDLE_DELETION
#endif
#ifdef REFERENCE_BY_POINTER
#undef REFERENCE_BY_POINTER
#endif
#ifdef BAD_POOL_HEADER
#undef BAD_POOL_HEADER
#endif
#ifdef MEMORY_MANAGEMENT
#undef MEMORY_MANAGEMENT
#endif
#ifdef PFN_SHARE_COUNT
#undef PFN_SHARE_COUNT
#endif
#ifdef PFN_REFERENCE_COUNT
#undef PFN_REFERENCE_COUNT
#endif
#ifdef NO_SPIN_LOCK_AVAILABLE
#undef NO_SPIN_LOCK_AVAILABLE
#endif
#ifdef KMODE_EXCEPTION_NOT_HANDLED
#undef KMODE_EXCEPTION_NOT_HANDLED
#endif
#ifdef SHARED_RESOURCE_CONV_ERROR
#undef SHARED_RESOURCE_CONV_ERROR
#endif
#ifdef KERNEL_APC_PENDING_DURING_EXIT
#undef KERNEL_APC_PENDING_DURING_EXIT
#endif
#ifdef QUOTA_UNDERFLOW
#undef QUOTA_UNDERFLOW
#endif
#ifdef FILE_SYSTEM
#undef FILE_SYSTEM
#endif
#ifdef FAT_FILE_SYSTEM
#undef FAT_FILE_SYSTEM
#endif
#ifdef NTFS_FILE_SYSTEM
#undef NTFS_FILE_SYSTEM
#endif
#ifdef NPFS_FILE_SYSTEM
#undef NPFS_FILE_SYSTEM
#endif
#ifdef CDFS_FILE_SYSTEM
#undef CDFS_FILE_SYSTEM
#endif
#ifdef RDR_FILE_SYSTEM
#undef RDR_FILE_SYSTEM
#endif
#ifdef CORRUPT_ACCESS_TOKEN
#undef CORRUPT_ACCESS_TOKEN
#endif
#ifdef SECURITY_SYSTEM
#undef SECURITY_SYSTEM
#endif
#ifdef INCONSISTENT_IRP
#undef INCONSISTENT_IRP
#endif
#ifdef PANIC_STACK_SWITCH
#undef PANIC_STACK_SWITCH
#endif
#ifdef PORT_DRIVER_INTERNAL
#undef PORT_DRIVER_INTERNAL
#endif
#ifdef SCSI_DISK_DRIVER_INTERNAL
#undef SCSI_DISK_DRIVER_INTERNAL
#endif
#ifdef DATA_BUS_ERROR
#undef DATA_BUS_ERROR
#endif
#ifdef INSTRUCTION_BUS_ERROR
#undef INSTRUCTION_BUS_ERROR
#endif
#ifdef SET_OF_INVALID_CONTEXT
#undef SET_OF_INVALID_CONTEXT
#endif
#ifdef PHASE0_INITIALIZATION_FAILED
#undef PHASE0_INITIALIZATION_FAILED
#endif
#ifdef PHASE1_INITIALIZATION_FAILED
#undef PHASE1_INITIALIZATION_FAILED
#endif
#ifdef UNEXPECTED_INITIALIZATION_CALL
#undef UNEXPECTED_INITIALIZATION_CALL
#endif
#ifdef CACHE_MANAGER
#undef CACHE_MANAGER
#endif
#ifdef NO_MORE_IRP_STACK_LOCATIONS
#undef NO_MORE_IRP_STACK_LOCATIONS
#endif
#ifdef DEVICE_REFERENCE_COUNT_NOT_ZERO
#undef DEVICE_REFERENCE_COUNT_NOT_ZERO
#endif
#ifdef FLOPPY_INTERNAL_ERROR
#undef FLOPPY_INTERNAL_ERROR
#endif
#ifdef SERIAL_DRIVER_INTERNAL
#undef SERIAL_DRIVER_INTERNAL
#endif
#ifdef SYSTEM_EXIT_OWNED_MUTEX
#undef SYSTEM_EXIT_OWNED_MUTEX
#endif
#ifdef SYSTEM_UNWIND_PREVIOUS_USER
#undef SYSTEM_UNWIND_PREVIOUS_USER
#endif
#ifdef SYSTEM_SERVICE_EXCEPTION
#undef SYSTEM_SERVICE_EXCEPTION
#endif
#ifdef INTERRUPT_UNWIND_ATTEMPTED
#undef INTERRUPT_UNWIND_ATTEMPTED
#endif
#ifdef INTERRUPT_EXCEPTION_NOT_HANDLED
#undef INTERRUPT_EXCEPTION_NOT_HANDLED
#endif
#ifdef MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED
#undef MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED
#endif
#ifdef NO_MORE_SYSTEM_PTES
#undef NO_MORE_SYSTEM_PTES
#endif
#ifdef TARGET_MDL_TOO_SMALL
#undef TARGET_MDL_TOO_SMALL
#endif
#ifdef MUST_SUCCEED_POOL_EMPTY
#undef MUST_SUCCEED_POOL_EMPTY
#endif
#ifdef ATDISK_DRIVER_INTERNAL
#undef ATDISK_DRIVER_INTERNAL
#endif
#ifdef NO_SUCH_PARTITION
#undef NO_SUCH_PARTITION
#endif
#ifdef MULTIPLE_IRP_COMPLETE_REQUESTS
#undef MULTIPLE_IRP_COMPLETE_REQUESTS
#endif
#ifdef INSUFFICIENT_SYSTEM_MAP_REGS
#undef INSUFFICIENT_SYSTEM_MAP_REGS
#endif
#ifdef DEREF_UNKNOWN_LOGON_SESSION
#undef DEREF_UNKNOWN_LOGON_SESSION
#endif
#ifdef REF_UNKNOWN_LOGON_SESSION
#undef REF_UNKNOWN_LOGON_SESSION
#endif
#ifdef CANCEL_STATE_IN_COMPLETED_IRP
#undef CANCEL_STATE_IN_COMPLETED_IRP
#endif
#ifdef PAGE_FAULT_WITH_INTERRUPTS_OFF
#undef PAGE_FAULT_WITH_INTERRUPTS_OFF
#endif
#ifdef IRQL_GT_ZERO_AT_SYSTEM_SERVICE
#undef IRQL_GT_ZERO_AT_SYSTEM_SERVICE
#endif
#ifdef STREAMS_INTERNAL_ERROR
#undef STREAMS_INTERNAL_ERROR
#endif
#ifdef FATAL_UNHANDLED_HARD_ERROR
#undef FATAL_UNHANDLED_HARD_ERROR
#endif
#ifdef NO_PAGES_AVAILABLE
#undef NO_PAGES_AVAILABLE
#endif
#ifdef PFN_LIST_CORRUPT
#undef PFN_LIST_CORRUPT
#endif
#ifdef NDIS_INTERNAL_ERROR
#undef NDIS_INTERNAL_ERROR
#endif
#ifdef PAGE_FAULT_IN_NONPAGED_AREA
#undef PAGE_FAULT_IN_NONPAGED_AREA
#endif
#ifdef REGISTRY_ERROR
#undef REGISTRY_ERROR
#endif
#ifdef MAILSLOT_FILE_SYSTEM
#undef MAILSLOT_FILE_SYSTEM
#endif
#ifdef NO_BOOT_DEVICE
#undef NO_BOOT_DEVICE
#endif
#ifdef LM_SERVER_INTERNAL_ERROR
#undef LM_SERVER_INTERNAL_ERROR
#endif
#ifdef DATA_COHERENCY_EXCEPTION
#undef DATA_COHERENCY_EXCEPTION
#endif
#ifdef INSTRUCTION_COHERENCY_EXCEPTION
#undef INSTRUCTION_COHERENCY_EXCEPTION
#endif
#ifdef XNS_INTERNAL_ERROR
#undef XNS_INTERNAL_ERROR
#endif
#ifdef FTDISK_INTERNAL_ERROR
#undef FTDISK_INTERNAL_ERROR
#endif
#ifdef VOLMGRX_INTERNAL_ERROR
#undef VOLMGRX_INTERNAL_ERROR
#endif
#ifdef PINBALL_FILE_SYSTEM
#undef PINBALL_FILE_SYSTEM
#endif
#ifdef CRITICAL_SERVICE_FAILED
#undef CRITICAL_SERVICE_FAILED
#endif
#ifdef SET_ENV_VAR_FAILED
#undef SET_ENV_VAR_FAILED
#endif
#ifdef HAL_INITIALIZATION_FAILED
#undef HAL_INITIALIZATION_FAILED
#endif
#ifdef UNSUPPORTED_PROCESSOR
#undef UNSUPPORTED_PROCESSOR
#endif
#ifdef OBJECT_INITIALIZATION_FAILED
#undef OBJECT_INITIALIZATION_FAILED
#endif
#ifdef SECURITY_INITIALIZATION_FAILED
#undef SECURITY_INITIALIZATION_FAILED
#endif
#ifdef PROCESS_INITIALIZATION_FAILED
#undef PROCESS_INITIALIZATION_FAILED
#endif
#ifdef HAL1_INITIALIZATION_FAILED
#undef HAL1_INITIALIZATION_FAILED
#endif
#ifdef OBJECT1_INITIALIZATION_FAILED
#undef OBJECT1_INITIALIZATION_FAILED
#endif
#ifdef SECURITY1_INITIALIZATION_FAILED
#undef SECURITY1_INITIALIZATION_FAILED
#endif
#ifdef SYMBOLIC_INITIALIZATION_FAILED
#undef SYMBOLIC_INITIALIZATION_FAILED
#endif
#ifdef MEMORY1_INITIALIZATION_FAILED
#undef MEMORY1_INITIALIZATION_FAILED
#endif
#ifdef CACHE_INITIALIZATION_FAILED
#undef CACHE_INITIALIZATION_FAILED
#endif
#ifdef CONFIG_INITIALIZATION_FAILED
#undef CONFIG_INITIALIZATION_FAILED
#endif
#ifdef FILE_INITIALIZATION_FAILED
#undef FILE_INITIALIZATION_FAILED
#endif
#ifdef IO1_INITIALIZATION_FAILED
#undef IO1_INITIALIZATION_FAILED
#endif
#ifdef LPC_INITIALIZATION_FAILED
#undef LPC_INITIALIZATION_FAILED
#endif
#ifdef PROCESS1_INITIALIZATION_FAILED
#undef PROCESS1_INITIALIZATION_FAILED
#endif
#ifdef REFMON_INITIALIZATION_FAILED
#undef REFMON_INITIALIZATION_FAILED
#endif
#ifdef SESSION1_INITIALIZATION_FAILED
#undef SESSION1_INITIALIZATION_FAILED
#endif
#ifdef SESSION2_INITIALIZATION_FAILED
#undef SESSION2_INITIALIZATION_FAILED
#endif
#ifdef BOOTPROC_INITIALIZATION_FAILED
#undef BOOTPROC_INITIALIZATION_FAILED
#endif
#ifdef SESSION3_INITIALIZATION_FAILED
#undef SESSION3_INITIALIZATION_FAILED
#endif
#ifdef VSL_INITIALIZATION_FAILED
#undef VSL_INITIALIZATION_FAILED
#endif
#ifdef SESSION4_INITIALIZATION_FAILED
#undef SESSION4_INITIALIZATION_FAILED
#endif
#ifdef SOFT_RESTART_FATAL_ERROR
#undef SOFT_RESTART_FATAL_ERROR
#endif
#ifdef SESSION5_INITIALIZATION_FAILED
#undef SESSION5_INITIALIZATION_FAILED
#endif
#ifdef ASSIGN_DRIVE_LETTERS_FAILED
#undef ASSIGN_DRIVE_LETTERS_FAILED
#endif
#ifdef CONFIG_LIST_FAILED
#undef CONFIG_LIST_FAILED
#endif
#ifdef BAD_SYSTEM_CONFIG_INFO
#undef BAD_SYSTEM_CONFIG_INFO
#endif
#ifdef CANNOT_WRITE_CONFIGURATION
#undef CANNOT_WRITE_CONFIGURATION
#endif
#ifdef PROCESS_HAS_LOCKED_PAGES
#undef PROCESS_HAS_LOCKED_PAGES
#endif
#ifdef KERNEL_STACK_INPAGE_ERROR
#undef KERNEL_STACK_INPAGE_ERROR
#endif
#ifdef PHASE0_EXCEPTION
#undef PHASE0_EXCEPTION
#endif
#ifdef MISMATCHED_HAL
#undef MISMATCHED_HAL
#endif
#ifdef KERNEL_DATA_INPAGE_ERROR
#undef KERNEL_DATA_INPAGE_ERROR
#endif
#ifdef INACCESSIBLE_BOOT_DEVICE
#undef INACCESSIBLE_BOOT_DEVICE
#endif
#ifdef BUGCODE_NDIS_DRIVER
#undef BUGCODE_NDIS_DRIVER
#endif
#ifdef INSTALL_MORE_MEMORY
#undef INSTALL_MORE_MEMORY
#endif
#ifdef SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
#undef SYSTEM_THREAD_EXCEPTION_NOT_HANDLED
#endif
#ifdef UNEXPECTED_KERNEL_MODE_TRAP
#undef UNEXPECTED_KERNEL_MODE_TRAP
#endif
#ifdef NMI_HARDWARE_FAILURE
#undef NMI_HARDWARE_FAILURE
#endif
#ifdef SPIN_LOCK_INIT_FAILURE
#undef SPIN_LOCK_INIT_FAILURE
#endif
#ifdef DFS_FILE_SYSTEM
#undef DFS_FILE_SYSTEM
#endif
#ifdef OFS_FILE_SYSTEM
#undef OFS_FILE_SYSTEM
#endif
#ifdef RECOM_DRIVER
#undef RECOM_DRIVER
#endif
#ifdef SETUP_FAILURE
#undef SETUP_FAILURE
#endif
#ifdef AUDIT_FAILURE
#undef AUDIT_FAILURE
#endif
#ifdef MBR_CHECKSUM_MISMATCH
#undef MBR_CHECKSUM_MISMATCH
#endif
#ifdef KERNEL_MODE_EXCEPTION_NOT_HANDLED
#undef KERNEL_MODE_EXCEPTION_NOT_HANDLED
#endif
#ifdef PP0_INITIALIZATION_FAILED
#undef PP0_INITIALIZATION_FAILED
#endif
#ifdef PP1_INITIALIZATION_FAILED
#undef PP1_INITIALIZATION_FAILED
#endif
#ifdef WIN32K_INIT_OR_RIT_FAILURE
#undef WIN32K_INIT_OR_RIT_FAILURE
#endif
#ifdef UP_DRIVER_ON_MP_SYSTEM
#undef UP_DRIVER_ON_MP_SYSTEM
#endif
#ifdef INVALID_KERNEL_HANDLE
#undef INVALID_KERNEL_HANDLE
#endif
#ifdef KERNEL_STACK_LOCKED_AT_EXIT
#undef KERNEL_STACK_LOCKED_AT_EXIT
#endif
#ifdef PNP_INTERNAL_ERROR
#undef PNP_INTERNAL_ERROR
#endif
#ifdef INVALID_WORK_QUEUE_ITEM
#undef INVALID_WORK_QUEUE_ITEM
#endif
#ifdef BOUND_IMAGE_UNSUPPORTED
#undef BOUND_IMAGE_UNSUPPORTED
#endif
#ifdef END_OF_NT_EVALUATION_PERIOD
#undef END_OF_NT_EVALUATION_PERIOD
#endif
#ifdef INVALID_REGION_OR_SEGMENT
#undef INVALID_REGION_OR_SEGMENT
#endif
#ifdef SYSTEM_LICENSE_VIOLATION
#undef SYSTEM_LICENSE_VIOLATION
#endif
#ifdef UDFS_FILE_SYSTEM
#undef UDFS_FILE_SYSTEM
#endif
#ifdef MACHINE_CHECK_EXCEPTION
#undef MACHINE_CHECK_EXCEPTION
#endif
#ifdef USER_MODE_HEALTH_MONITOR
#undef USER_MODE_HEALTH_MONITOR
#endif
#ifdef DRIVER_POWER_STATE_FAILURE
#undef DRIVER_POWER_STATE_FAILURE
#endif
#ifdef INTERNAL_POWER_ERROR
#undef INTERNAL_POWER_ERROR
#endif
#ifdef PCI_BUS_DRIVER_INTERNAL
#undef PCI_BUS_DRIVER_INTERNAL
#endif
#ifdef MEMORY_IMAGE_CORRUPT
#undef MEMORY_IMAGE_CORRUPT
#endif
#ifdef ACPI_DRIVER_INTERNAL
#undef ACPI_DRIVER_INTERNAL
#endif
#ifdef CNSS_FILE_SYSTEM_FILTER
#undef CNSS_FILE_SYSTEM_FILTER
#endif
#ifdef ACPI_BIOS_ERROR
#undef ACPI_BIOS_ERROR
#endif
#ifdef FP_EMULATION_ERROR
#undef FP_EMULATION_ERROR
#endif
#ifdef BAD_EXHANDLE
#undef BAD_EXHANDLE
#endif
#ifdef BOOTING_IN_SAFEMODE_MINIMAL
#undef BOOTING_IN_SAFEMODE_MINIMAL
#endif
#ifdef BOOTING_IN_SAFEMODE_NETWORK
#undef BOOTING_IN_SAFEMODE_NETWORK
#endif
#ifdef BOOTING_IN_SAFEMODE_DSREPAIR
#undef BOOTING_IN_SAFEMODE_DSREPAIR
#endif
#ifdef SESSION_HAS_VALID_POOL_ON_EXIT
#undef SESSION_HAS_VALID_POOL_ON_EXIT
#endif
#ifdef HAL_MEMORY_ALLOCATION
#undef HAL_MEMORY_ALLOCATION
#endif
#ifdef BGI_DETECTED_VIOLATION
#undef BGI_DETECTED_VIOLATION
#endif
#ifdef VIDEO_DRIVER_INIT_FAILURE
#undef VIDEO_DRIVER_INIT_FAILURE
#endif
#ifdef BOOTLOG_LOADED
#undef BOOTLOG_LOADED
#endif
#ifdef BOOTLOG_NOT_LOADED
#undef BOOTLOG_NOT_LOADED
#endif
#ifdef BOOTLOG_ENABLED
#undef BOOTLOG_ENABLED
#endif
#ifdef ATTEMPTED_SWITCH_FROM_DPC
#undef ATTEMPTED_SWITCH_FROM_DPC
#endif
#ifdef CHIPSET_DETECTED_ERROR
#undef CHIPSET_DETECTED_ERROR
#endif
#ifdef SESSION_HAS_VALID_VIEWS_ON_EXIT
#undef SESSION_HAS_VALID_VIEWS_ON_EXIT
#endif
#ifdef NETWORK_BOOT_INITIALIZATION_FAILED
#undef NETWORK_BOOT_INITIALIZATION_FAILED
#endif
#ifdef NETWORK_BOOT_DUPLICATE_ADDRESS
#undef NETWORK_BOOT_DUPLICATE_ADDRESS
#endif
#ifdef INVALID_HIBERNATED_STATE
#undef INVALID_HIBERNATED_STATE
#endif
#ifdef ATTEMPTED_WRITE_TO_READONLY_MEMORY
#undef ATTEMPTED_WRITE_TO_READONLY_MEMORY
#endif
#ifdef MUTEX_ALREADY_OWNED
#undef MUTEX_ALREADY_OWNED
#endif
#ifdef PCI_CONFIG_SPACE_ACCESS_FAILURE
#undef PCI_CONFIG_SPACE_ACCESS_FAILURE
#endif
#ifdef SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION
#undef SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION
#endif
#ifdef BAD_POOL_CALLER
#undef BAD_POOL_CALLER
#endif
#ifdef SYSTEM_IMAGE_BAD_SIGNATURE
#undef SYSTEM_IMAGE_BAD_SIGNATURE
#endif
#ifdef DRIVER_VERIFIER_DETECTED_VIOLATION
#undef DRIVER_VERIFIER_DETECTED_VIOLATION
#endif
#ifdef DRIVER_CORRUPTED_EXPOOL
#undef DRIVER_CORRUPTED_EXPOOL
#endif
#ifdef DRIVER_CAUGHT_MODIFYING_FREED_POOL
#undef DRIVER_CAUGHT_MODIFYING_FREED_POOL
#endif
#ifdef TIMER_OR_DPC_INVALID
#undef TIMER_OR_DPC_INVALID
#endif
#ifdef IRQL_UNEXPECTED_VALUE
#undef IRQL_UNEXPECTED_VALUE
#endif
#ifdef DRIVER_VERIFIER_IOMANAGER_VIOLATION
#undef DRIVER_VERIFIER_IOMANAGER_VIOLATION
#endif
#ifdef PNP_DETECTED_FATAL_ERROR
#undef PNP_DETECTED_FATAL_ERROR
#endif
#ifdef DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS
#undef DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS
#endif
#ifdef PAGE_FAULT_IN_FREED_SPECIAL_POOL
#undef PAGE_FAULT_IN_FREED_SPECIAL_POOL
#endif
#ifdef PAGE_FAULT_BEYOND_END_OF_ALLOCATION
#undef PAGE_FAULT_BEYOND_END_OF_ALLOCATION
#endif
#ifdef DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS
#undef DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS
#endif
#ifdef TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE
#undef TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE
#endif
#ifdef DRIVER_CORRUPTED_MMPOOL
#undef DRIVER_CORRUPTED_MMPOOL
#endif
#ifdef DRIVER_IRQL_NOT_LESS_OR_EQUAL
#undef DRIVER_IRQL_NOT_LESS_OR_EQUAL
#endif
#ifdef BUGCODE_ID_DRIVER
#undef BUGCODE_ID_DRIVER
#endif
#ifdef DRIVER_PORTION_MUST_BE_NONPAGED
#undef DRIVER_PORTION_MUST_BE_NONPAGED
#endif
#ifdef SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD
#undef SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD
#endif
#ifdef DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL
#undef DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL
#endif
#ifdef DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION
#undef DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION
#endif
#ifdef DRIVER_UNMAPPING_INVALID_VIEW
#undef DRIVER_UNMAPPING_INVALID_VIEW
#endif
#ifdef DRIVER_USED_EXCESSIVE_PTES
#undef DRIVER_USED_EXCESSIVE_PTES
#endif
#ifdef LOCKED_PAGES_TRACKER_CORRUPTION
#undef LOCKED_PAGES_TRACKER_CORRUPTION
#endif
#ifdef SYSTEM_PTE_MISUSE
#undef SYSTEM_PTE_MISUSE
#endif
#ifdef DRIVER_CORRUPTED_SYSPTES
#undef DRIVER_CORRUPTED_SYSPTES
#endif
#ifdef DRIVER_INVALID_STACK_ACCESS
#undef DRIVER_INVALID_STACK_ACCESS
#endif
#ifdef POOL_CORRUPTION_IN_FILE_AREA
#undef POOL_CORRUPTION_IN_FILE_AREA
#endif
#ifdef IMPERSONATING_WORKER_THREAD
#undef IMPERSONATING_WORKER_THREAD
#endif
#ifdef ACPI_BIOS_FATAL_ERROR
#undef ACPI_BIOS_FATAL_ERROR
#endif
#ifdef WORKER_THREAD_RETURNED_AT_BAD_IRQL
#undef WORKER_THREAD_RETURNED_AT_BAD_IRQL
#endif
#ifdef MANUALLY_INITIATED_CRASH
#undef MANUALLY_INITIATED_CRASH
#endif
#ifdef RESOURCE_NOT_OWNED
#undef RESOURCE_NOT_OWNED
#endif
#ifdef WORKER_INVALID
#undef WORKER_INVALID
#endif
#ifdef POWER_FAILURE_SIMULATE
#undef POWER_FAILURE_SIMULATE
#endif
#ifdef DRIVER_VERIFIER_DMA_VIOLATION
#undef DRIVER_VERIFIER_DMA_VIOLATION
#endif
#ifdef INVALID_FLOATING_POINT_STATE
#undef INVALID_FLOATING_POINT_STATE
#endif
#ifdef INVALID_CANCEL_OF_FILE_OPEN
#undef INVALID_CANCEL_OF_FILE_OPEN
#endif
#ifdef ACTIVE_EX_WORKER_THREAD_TERMINATION
#undef ACTIVE_EX_WORKER_THREAD_TERMINATION
#endif
#ifdef THREAD_STUCK_IN_DEVICE_DRIVER
#undef THREAD_STUCK_IN_DEVICE_DRIVER
#endif
#ifdef DIRTY_MAPPED_PAGES_CONGESTION
#undef DIRTY_MAPPED_PAGES_CONGESTION
#endif
#ifdef SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT
#undef SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT
#endif
#ifdef UNMOUNTABLE_BOOT_VOLUME
#undef UNMOUNTABLE_BOOT_VOLUME
#endif
#ifdef CRITICAL_PROCESS_DIED
#undef CRITICAL_PROCESS_DIED
#endif
#ifdef STORAGE_MINIPORT_ERROR
#undef STORAGE_MINIPORT_ERROR
#endif
#ifdef SCSI_VERIFIER_DETECTED_VIOLATION
#undef SCSI_VERIFIER_DETECTED_VIOLATION
#endif
#ifdef HARDWARE_INTERRUPT_STORM
#undef HARDWARE_INTERRUPT_STORM
#endif
#ifdef DISORDERLY_SHUTDOWN
#undef DISORDERLY_SHUTDOWN
#endif
#ifdef CRITICAL_OBJECT_TERMINATION
#undef CRITICAL_OBJECT_TERMINATION
#endif
#ifdef FLTMGR_FILE_SYSTEM
#undef FLTMGR_FILE_SYSTEM
#endif
#ifdef PCI_VERIFIER_DETECTED_VIOLATION
#undef PCI_VERIFIER_DETECTED_VIOLATION
#endif
#ifdef DRIVER_OVERRAN_STACK_BUFFER
#undef DRIVER_OVERRAN_STACK_BUFFER
#endif
#ifdef RAMDISK_BOOT_INITIALIZATION_FAILED
#undef RAMDISK_BOOT_INITIALIZATION_FAILED
#endif
#ifdef DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN
#undef DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN
#endif
#ifdef HTTP_DRIVER_CORRUPTED
#undef HTTP_DRIVER_CORRUPTED
#endif
#ifdef RECURSIVE_MACHINE_CHECK
#undef RECURSIVE_MACHINE_CHECK
#endif
#ifdef ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY
#undef ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY
#endif
#ifdef DIRTY_NOWRITE_PAGES_CONGESTION
#undef DIRTY_NOWRITE_PAGES_CONGESTION
#endif
#ifdef BUGCODE_USB_DRIVER
#undef BUGCODE_USB_DRIVER
#endif
#ifdef RESERVE_QUEUE_OVERFLOW
#undef RESERVE_QUEUE_OVERFLOW
#endif
#ifdef LOADER_BLOCK_MISMATCH
#undef LOADER_BLOCK_MISMATCH
#endif
#ifdef CLOCK_WATCHDOG_TIMEOUT
#undef CLOCK_WATCHDOG_TIMEOUT
#endif
#ifdef DPC_WATCHDOG_TIMEOUT
#undef DPC_WATCHDOG_TIMEOUT
#endif
#ifdef MUP_FILE_SYSTEM
#undef MUP_FILE_SYSTEM
#endif
#ifdef AGP_INVALID_ACCESS
#undef AGP_INVALID_ACCESS
#endif
#ifdef AGP_GART_CORRUPTION
#undef AGP_GART_CORRUPTION
#endif
#ifdef AGP_ILLEGALLY_REPROGRAMMED
#undef AGP_ILLEGALLY_REPROGRAMMED
#endif
#ifdef KERNEL_EXPAND_STACK_ACTIVE
#undef KERNEL_EXPAND_STACK_ACTIVE
#endif
#ifdef THIRD_PARTY_FILE_SYSTEM_FAILURE
#undef THIRD_PARTY_FILE_SYSTEM_FAILURE
#endif
#ifdef CRITICAL_STRUCTURE_CORRUPTION
#undef CRITICAL_STRUCTURE_CORRUPTION
#endif
#ifdef APP_TAGGING_INITIALIZATION_FAILED
#undef APP_TAGGING_INITIALIZATION_FAILED
#endif
#ifdef DFSC_FILE_SYSTEM
#undef DFSC_FILE_SYSTEM
#endif
#ifdef FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION
#undef FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION
#endif
#ifdef WDF_VIOLATION
#undef WDF_VIOLATION
#endif
#ifdef VIDEO_MEMORY_MANAGEMENT_INTERNAL
#undef VIDEO_MEMORY_MANAGEMENT_INTERNAL
#endif
#ifdef DRIVER_INVALID_CRUNTIME_PARAMETER
#undef DRIVER_INVALID_CRUNTIME_PARAMETER
#endif
#ifdef RECURSIVE_NMI
#undef RECURSIVE_NMI
#endif
#ifdef MSRPC_STATE_VIOLATION
#undef MSRPC_STATE_VIOLATION
#endif
#ifdef VIDEO_DXGKRNL_FATAL_ERROR
#undef VIDEO_DXGKRNL_FATAL_ERROR
#endif
#ifdef VIDEO_SHADOW_DRIVER_FATAL_ERROR
#undef VIDEO_SHADOW_DRIVER_FATAL_ERROR
#endif
#ifdef AGP_INTERNAL
#undef AGP_INTERNAL
#endif
#ifdef VIDEO_TDR_FAILURE
#undef VIDEO_TDR_FAILURE
#endif
#ifdef VIDEO_TDR_TIMEOUT_DETECTED
#undef VIDEO_TDR_TIMEOUT_DETECTED
#endif
#ifdef NTHV_GUEST_ERROR
#undef NTHV_GUEST_ERROR
#endif
#ifdef VIDEO_SCHEDULER_INTERNAL_ERROR
#undef VIDEO_SCHEDULER_INTERNAL_ERROR
#endif
#ifdef EM_INITIALIZATION_ERROR
#undef EM_INITIALIZATION_ERROR
#endif
#ifdef DRIVER_RETURNED_HOLDING_CANCEL_LOCK
#undef DRIVER_RETURNED_HOLDING_CANCEL_LOCK
#endif
#ifdef ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE
#undef ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE
#endif
#ifdef EVENT_TRACING_FATAL_ERROR
#undef EVENT_TRACING_FATAL_ERROR
#endif
#ifdef TOO_MANY_RECURSIVE_FAULTS
#undef TOO_MANY_RECURSIVE_FAULTS
#endif
#ifdef INVALID_DRIVER_HANDLE
#undef INVALID_DRIVER_HANDLE
#endif
#ifdef BITLOCKER_FATAL_ERROR
#undef BITLOCKER_FATAL_ERROR
#endif
#ifdef DRIVER_VIOLATION
#undef DRIVER_VIOLATION
#endif
#ifdef WHEA_INTERNAL_ERROR
#undef WHEA_INTERNAL_ERROR
#endif
#ifdef CRYPTO_SELF_TEST_FAILURE
#undef CRYPTO_SELF_TEST_FAILURE
#endif
#ifdef WHEA_UNCORRECTABLE_ERROR
#undef WHEA_UNCORRECTABLE_ERROR
#endif
#ifdef NMR_INVALID_STATE
#undef NMR_INVALID_STATE
#endif
#ifdef NETIO_INVALID_POOL_CALLER
#undef NETIO_INVALID_POOL_CALLER
#endif
#ifdef PAGE_NOT_ZERO
#undef PAGE_NOT_ZERO
#endif
#ifdef WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY
#undef WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY
#endif
#ifdef WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY
#undef WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY
#endif
#ifdef MUI_NO_VALID_SYSTEM_LANGUAGE
#undef MUI_NO_VALID_SYSTEM_LANGUAGE
#endif
#ifdef FAULTY_HARDWARE_CORRUPTED_PAGE
#undef FAULTY_HARDWARE_CORRUPTED_PAGE
#endif
#ifdef EXFAT_FILE_SYSTEM
#undef EXFAT_FILE_SYSTEM
#endif
#ifdef VOLSNAP_OVERLAPPED_TABLE_ACCESS
#undef VOLSNAP_OVERLAPPED_TABLE_ACCESS
#endif
#ifdef INVALID_MDL_RANGE
#undef INVALID_MDL_RANGE
#endif
#ifdef VHD_BOOT_INITIALIZATION_FAILED
#undef VHD_BOOT_INITIALIZATION_FAILED
#endif
#ifdef DYNAMIC_ADD_PROCESSOR_MISMATCH
#undef DYNAMIC_ADD_PROCESSOR_MISMATCH
#endif
#ifdef INVALID_EXTENDED_PROCESSOR_STATE
#undef INVALID_EXTENDED_PROCESSOR_STATE
#endif
#ifdef RESOURCE_OWNER_POINTER_INVALID
#undef RESOURCE_OWNER_POINTER_INVALID
#endif
#ifdef DPC_WATCHDOG_VIOLATION
#undef DPC_WATCHDOG_VIOLATION
#endif
#ifdef DRIVE_EXTENDER
#undef DRIVE_EXTENDER
#endif
#ifdef REGISTRY_FILTER_DRIVER_EXCEPTION
#undef REGISTRY_FILTER_DRIVER_EXCEPTION
#endif
#ifdef VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE
#undef VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE
#endif
#ifdef WIN32K_HANDLE_MANAGER
#undef WIN32K_HANDLE_MANAGER
#endif
#ifdef GPIO_CONTROLLER_DRIVER_ERROR
#undef GPIO_CONTROLLER_DRIVER_ERROR
#endif
#ifdef KERNEL_SECURITY_CHECK_FAILURE
#undef KERNEL_SECURITY_CHECK_FAILURE
#endif
#ifdef KERNEL_MODE_HEAP_CORRUPTION
#undef KERNEL_MODE_HEAP_CORRUPTION
#endif
#ifdef PASSIVE_INTERRUPT_ERROR
#undef PASSIVE_INTERRUPT_ERROR
#endif
#ifdef INVALID_IO_BOOST_STATE
#undef INVALID_IO_BOOST_STATE
#endif
#ifdef CRITICAL_INITIALIZATION_FAILURE
#undef CRITICAL_INITIALIZATION_FAILURE
#endif
#ifdef ERRATA_WORKAROUND_UNSUCCESSFUL
#undef ERRATA_WORKAROUND_UNSUCCESSFUL
#endif
#ifdef STORAGE_DEVICE_ABNORMALITY_DETECTED
#undef STORAGE_DEVICE_ABNORMALITY_DETECTED
#endif
#ifdef VIDEO_ENGINE_TIMEOUT_DETECTED
#undef VIDEO_ENGINE_TIMEOUT_DETECTED
#endif
#ifdef VIDEO_TDR_APPLICATION_BLOCKED
#undef VIDEO_TDR_APPLICATION_BLOCKED
#endif
#ifdef PROCESSOR_DRIVER_INTERNAL
#undef PROCESSOR_DRIVER_INTERNAL
#endif
#ifdef BUGCODE_USB3_DRIVER
#undef BUGCODE_USB3_DRIVER
#endif
#ifdef SECURE_BOOT_VIOLATION
#undef SECURE_BOOT_VIOLATION
#endif
#ifdef NDIS_NET_BUFFER_LIST_INFO_ILLEGALLY_TRANSFERRED
#undef NDIS_NET_BUFFER_LIST_INFO_ILLEGALLY_TRANSFERRED
#endif
#ifdef ABNORMAL_RESET_DETECTED
#undef ABNORMAL_RESET_DETECTED
#endif
#ifdef IO_OBJECT_INVALID
#undef IO_OBJECT_INVALID
#endif
#ifdef REFS_FILE_SYSTEM
#undef REFS_FILE_SYSTEM
#endif
#ifdef KERNEL_WMI_INTERNAL
#undef KERNEL_WMI_INTERNAL
#endif
#ifdef SOC_SUBSYSTEM_FAILURE
#undef SOC_SUBSYSTEM_FAILURE
#endif
#ifdef FATAL_ABNORMAL_RESET_ERROR
#undef FATAL_ABNORMAL_RESET_ERROR
#endif
#ifdef EXCEPTION_SCOPE_INVALID
#undef EXCEPTION_SCOPE_INVALID
#endif
#ifdef SOC_CRITICAL_DEVICE_REMOVED
#undef SOC_CRITICAL_DEVICE_REMOVED
#endif
#ifdef PDC_WATCHDOG_TIMEOUT
#undef PDC_WATCHDOG_TIMEOUT
#endif
#ifdef TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK
#undef TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK
#endif
#ifdef UNSUPPORTED_INSTRUCTION_MODE
#undef UNSUPPORTED_INSTRUCTION_MODE
#endif
#ifdef INVALID_PUSH_LOCK_FLAGS
#undef INVALID_PUSH_LOCK_FLAGS
#endif
#ifdef KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION
#undef KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION
#endif
#ifdef UNEXPECTED_STORE_EXCEPTION
#undef UNEXPECTED_STORE_EXCEPTION
#endif
#ifdef OS_DATA_TAMPERING
#undef OS_DATA_TAMPERING
#endif
#ifdef WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP
#undef WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP
#endif
#ifdef KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION
#undef KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION
#endif
#ifdef ILLEGAL_IOMMU_PAGE_FAULT
#undef ILLEGAL_IOMMU_PAGE_FAULT
#endif
#ifdef HAL_ILLEGAL_IOMMU_PAGE_FAULT
#undef HAL_ILLEGAL_IOMMU_PAGE_FAULT
#endif
#ifdef SDBUS_INTERNAL_ERROR
#undef SDBUS_INTERNAL_ERROR
#endif
#ifdef WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE
#undef WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE
#endif
#ifdef PDC_WATCHDOG_TIMEOUT_LIVEDUMP
#undef PDC_WATCHDOG_TIMEOUT_LIVEDUMP
#endif
#ifdef SOC_SUBSYSTEM_FAILURE_LIVEDUMP
#undef SOC_SUBSYSTEM_FAILURE_LIVEDUMP
#endif
#ifdef BUGCODE_NDIS_DRIVER_LIVE_DUMP
#undef BUGCODE_NDIS_DRIVER_LIVE_DUMP
#endif
#ifdef CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP
#undef CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP
#endif
#ifdef WIN32K_ATOMIC_CHECK_FAILURE
#undef WIN32K_ATOMIC_CHECK_FAILURE
#endif
#ifdef LIVE_SYSTEM_DUMP
#undef LIVE_SYSTEM_DUMP
#endif
#ifdef KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE
#undef KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE
#endif
#ifdef WORKER_THREAD_TEST_CONDITION
#undef WORKER_THREAD_TEST_CONDITION
#endif
#ifdef WIN32K_CRITICAL_FAILURE
#undef WIN32K_CRITICAL_FAILURE
#endif
#ifdef CLUSTER_CSV_STATUS_IO_TIMEOUT_LIVEDUMP
#undef CLUSTER_CSV_STATUS_IO_TIMEOUT_LIVEDUMP
#endif
#ifdef CLUSTER_RESOURCE_CALL_TIMEOUT_LIVEDUMP
#undef CLUSTER_RESOURCE_CALL_TIMEOUT_LIVEDUMP
#endif
#ifdef CLUSTER_CSV_SNAPSHOT_DEVICE_INFO_TIMEOUT_LIVEDUMP
#undef CLUSTER_CSV_SNAPSHOT_DEVICE_INFO_TIMEOUT_LIVEDUMP
#endif
#ifdef CLUSTER_CSV_STATE_TRANSITION_TIMEOUT_LIVEDUMP
#undef CLUSTER_CSV_STATE_TRANSITION_TIMEOUT_LIVEDUMP
#endif
#ifdef CLUSTER_CSV_VOLUME_ARRIVAL_LIVEDUMP
#undef CLUSTER_CSV_VOLUME_ARRIVAL_LIVEDUMP
#endif
#ifdef CLUSTER_CSV_VOLUME_REMOVAL_LIVEDUMP
#undef CLUSTER_CSV_VOLUME_REMOVAL_LIVEDUMP
#endif
#ifdef CLUSTER_CSV_CLUSTER_WATCHDOG_LIVEDUMP
#undef CLUSTER_CSV_CLUSTER_WATCHDOG_LIVEDUMP
#endif
#ifdef INVALID_RUNDOWN_PROTECTION_FLAGS
#undef INVALID_RUNDOWN_PROTECTION_FLAGS
#endif
#ifdef INVALID_SLOT_ALLOCATOR_FLAGS
#undef INVALID_SLOT_ALLOCATOR_FLAGS
#endif
#ifdef ERESOURCE_INVALID_RELEASE
#undef ERESOURCE_INVALID_RELEASE
#endif
#ifdef CLUSTER_CSV_STATE_TRANSITION_INTERVAL_TIMEOUT_LIVEDUMP
#undef CLUSTER_CSV_STATE_TRANSITION_INTERVAL_TIMEOUT_LIVEDUMP
#endif
#ifdef CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG
#undef CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG
#endif
#ifdef CRYPTO_LIBRARY_INTERNAL_ERROR
#undef CRYPTO_LIBRARY_INTERNAL_ERROR
#endif
#ifdef COREMSGCALL_INTERNAL_ERROR
#undef COREMSGCALL_INTERNAL_ERROR
#endif
#ifdef COREMSG_INTERNAL_ERROR
#undef COREMSG_INTERNAL_ERROR
#endif
#ifdef PREVIOUS_FATAL_ABNORMAL_RESET_ERROR
#undef PREVIOUS_FATAL_ABNORMAL_RESET_ERROR
#endif
#ifdef ELAM_DRIVER_DETECTED_FATAL_ERROR
#undef ELAM_DRIVER_DETECTED_FATAL_ERROR
#endif
#ifdef CLUSTER_CLUSPORT_STATUS_IO_TIMEOUT_LIVEDUMP
#undef CLUSTER_CLUSPORT_STATUS_IO_TIMEOUT_LIVEDUMP
#endif
#ifdef PROFILER_CONFIGURATION_ILLEGAL
#undef PROFILER_CONFIGURATION_ILLEGAL
#endif
#ifdef PDC_LOCK_WATCHDOG_LIVEDUMP
#undef PDC_LOCK_WATCHDOG_LIVEDUMP
#endif
#ifdef PDC_UNEXPECTED_REVOCATION_LIVEDUMP
#undef PDC_UNEXPECTED_REVOCATION_LIVEDUMP
#endif
#ifdef WVR_LIVEDUMP_REPLICATION_IOCONTEXT_TIMEOUT
#undef WVR_LIVEDUMP_REPLICATION_IOCONTEXT_TIMEOUT
#endif
#ifdef WVR_LIVEDUMP_STATE_TRANSITION_TIMEOUT
#undef WVR_LIVEDUMP_STATE_TRANSITION_TIMEOUT
#endif
#ifdef WVR_LIVEDUMP_RECOVERY_IOCONTEXT_TIMEOUT
#undef WVR_LIVEDUMP_RECOVERY_IOCONTEXT_TIMEOUT
#endif
#ifdef WVR_LIVEDUMP_APP_IO_TIMEOUT
#undef WVR_LIVEDUMP_APP_IO_TIMEOUT
#endif
#ifdef WVR_LIVEDUMP_MANUALLY_INITIATED
#undef WVR_LIVEDUMP_MANUALLY_INITIATED
#endif
#ifdef WVR_LIVEDUMP_STATE_FAILURE
#undef WVR_LIVEDUMP_STATE_FAILURE
#endif
#ifdef WVR_LIVEDUMP_CRITICAL_ERROR
#undef WVR_LIVEDUMP_CRITICAL_ERROR
#endif
#ifdef VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD
#undef VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD
#endif
#ifdef CLUSTER_CSVFS_LIVEDUMP
#undef CLUSTER_CSVFS_LIVEDUMP
#endif
#ifdef BAD_OBJECT_HEADER
#undef BAD_OBJECT_HEADER
#endif
#ifdef SILO_CORRUPT
#undef SILO_CORRUPT
#endif
#ifdef SECURE_KERNEL_ERROR
#undef SECURE_KERNEL_ERROR
#endif
#ifdef HYPERGUARD_VIOLATION
#undef HYPERGUARD_VIOLATION
#endif
#ifdef SECURE_FAULT_UNHANDLED
#undef SECURE_FAULT_UNHANDLED
#endif
#ifdef KERNEL_PARTITION_REFERENCE_VIOLATION
#undef KERNEL_PARTITION_REFERENCE_VIOLATION
#endif
#ifdef WIN32K_CRITICAL_FAILURE_LIVEDUMP
#undef WIN32K_CRITICAL_FAILURE_LIVEDUMP
#endif
#ifdef PF_DETECTED_CORRUPTION
#undef PF_DETECTED_CORRUPTION
#endif
#ifdef KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL
#undef KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL
#endif
#ifdef VIDEO_DXGKRNL_LIVEDUMP
#undef VIDEO_DXGKRNL_LIVEDUMP
#endif
#ifdef SAVER_NONRESPONSIVEPROCESS
#undef SAVER_NONRESPONSIVEPROCESS
#endif
#ifdef SMB_SERVER_LIVEDUMP
#undef SMB_SERVER_LIVEDUMP
#endif
#ifdef LOADER_ROLLBACK_DETECTED
#undef LOADER_ROLLBACK_DETECTED
#endif
#ifdef WIN32K_SECURITY_FAILURE
#undef WIN32K_SECURITY_FAILURE
#endif
#ifdef UFX_LIVEDUMP
#undef UFX_LIVEDUMP
#endif
#ifdef KERNEL_STORAGE_SLOT_IN_USE
#undef KERNEL_STORAGE_SLOT_IN_USE
#endif
#ifdef WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO
#undef WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO
#endif
#ifdef TTM_FATAL_ERROR
#undef TTM_FATAL_ERROR
#endif
#ifdef WIN32K_POWER_WATCHDOG_TIMEOUT
#undef WIN32K_POWER_WATCHDOG_TIMEOUT
#endif
#ifdef CLUSTER_SVHDX_LIVEDUMP
#undef CLUSTER_SVHDX_LIVEDUMP
#endif
#ifdef BUGCODE_NETADAPTER_DRIVER
#undef BUGCODE_NETADAPTER_DRIVER
#endif
#ifdef PDC_PRIVILEGE_CHECK_LIVEDUMP
#undef PDC_PRIVILEGE_CHECK_LIVEDUMP
#endif
#ifdef TTM_WATCHDOG_TIMEOUT
#undef TTM_WATCHDOG_TIMEOUT
#endif
#ifdef WIN32K_CALLOUT_WATCHDOG_LIVEDUMP
#undef WIN32K_CALLOUT_WATCHDOG_LIVEDUMP
#endif
#ifdef WIN32K_CALLOUT_WATCHDOG_BUGCHECK
#undef WIN32K_CALLOUT_WATCHDOG_BUGCHECK
#endif
#ifdef CALL_HAS_NOT_RETURNED_WATCHDOG_TIMEOUT_LIVEDUMP
#undef CALL_HAS_NOT_RETURNED_WATCHDOG_TIMEOUT_LIVEDUMP
#endif
#ifdef DRIPS_SW_HW_DIVERGENCE_LIVEDUMP
#undef DRIPS_SW_HW_DIVERGENCE_LIVEDUMP
#endif
#ifdef USB_DRIPS_BLOCKER_SURPRISE_REMOVAL_LIVEDUMP
#undef USB_DRIPS_BLOCKER_SURPRISE_REMOVAL_LIVEDUMP
#endif
#ifdef DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP
#undef DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP
#endif
#ifdef IO_THREADPOOL_DEADLOCK_LIVEDUMP
#undef IO_THREADPOOL_DEADLOCK_LIVEDUMP
#endif
#ifdef FAST_ERESOURCE_PRECONDITION_VIOLATION
#undef FAST_ERESOURCE_PRECONDITION_VIOLATION
#endif
#ifdef STORE_DATA_STRUCTURE_CORRUPTION
#undef STORE_DATA_STRUCTURE_CORRUPTION
#endif
#ifdef MANUALLY_INITIATED_POWER_BUTTON_HOLD
#undef MANUALLY_INITIATED_POWER_BUTTON_HOLD
#endif
#ifdef USER_MODE_HEALTH_MONITOR_LIVEDUMP
#undef USER_MODE_HEALTH_MONITOR_LIVEDUMP
#endif
#ifdef HYPERVISOR_WATCHDOG_TIMEOUT
#undef HYPERVISOR_WATCHDOG_TIMEOUT
#endif
#ifdef INVALID_SILO_DETACH
#undef INVALID_SILO_DETACH
#endif
#ifdef EXRESOURCE_TIMEOUT_LIVEDUMP
#undef EXRESOURCE_TIMEOUT_LIVEDUMP
#endif
#ifdef INVALID_CALLBACK_STACK_ADDRESS
#undef INVALID_CALLBACK_STACK_ADDRESS
#endif
#ifdef INVALID_KERNEL_STACK_ADDRESS
#undef INVALID_KERNEL_STACK_ADDRESS
#endif
#ifdef HARDWARE_WATCHDOG_TIMEOUT
#undef HARDWARE_WATCHDOG_TIMEOUT
#endif
#ifdef ACPI_FIRMWARE_WATCHDOG_TIMEOUT
#undef ACPI_FIRMWARE_WATCHDOG_TIMEOUT
#endif
#ifdef TELEMETRY_ASSERTS_LIVEDUMP
#undef TELEMETRY_ASSERTS_LIVEDUMP
#endif
#ifdef WORKER_THREAD_INVALID_STATE
#undef WORKER_THREAD_INVALID_STATE
#endif
#ifdef WFP_INVALID_OPERATION
#undef WFP_INVALID_OPERATION
#endif
#ifdef UCMUCSI_LIVEDUMP
#undef UCMUCSI_LIVEDUMP
#endif
#ifdef DRIVER_PNP_WATCHDOG
#undef DRIVER_PNP_WATCHDOG
#endif
#ifdef SAVER_MTBFCOMMANDTIMEOUT
#undef SAVER_MTBFCOMMANDTIMEOUT
#endif
#ifdef XBOX_ERACTRL_CS_TIMEOUT
#undef XBOX_ERACTRL_CS_TIMEOUT
#endif
#ifdef XBOX_CORRUPTED_IMAGE
#undef XBOX_CORRUPTED_IMAGE
#endif
#ifdef XBOX_INVERTED_FUNCTION_TABLE_OVERFLOW
#undef XBOX_INVERTED_FUNCTION_TABLE_OVERFLOW
#endif
#ifdef XBOX_CORRUPTED_IMAGE_BASE
#undef XBOX_CORRUPTED_IMAGE_BASE
#endif
#ifdef XBOX_360_SYSTEM_CRASH
#undef XBOX_360_SYSTEM_CRASH
#endif
#ifdef XBOX_360_SYSTEM_CRASH_RESERVED
#undef XBOX_360_SYSTEM_CRASH_RESERVED
#endif
#ifdef BC_BLUETOOTH_VERIFIER_FAULT
#undef BC_BLUETOOTH_VERIFIER_FAULT
#endif
#ifdef BC_BTHMINI_VERIFIER_FAULT
#undef BC_BTHMINI_VERIFIER_FAULT
#endif
#ifdef SAVER_SICKAPPLICATION
#undef SAVER_SICKAPPLICATION
#endif
#ifdef SAVER_UNSPECIFIED
#undef SAVER_UNSPECIFIED
#endif
#ifdef SAVER_BLANKSCREEN
#undef SAVER_BLANKSCREEN
#endif
#ifdef SAVER_INPUT
#undef SAVER_INPUT
#endif
#ifdef SAVER_WATCHDOG
#undef SAVER_WATCHDOG
#endif
#ifdef SAVER_STARTNOTVISIBLE
#undef SAVER_STARTNOTVISIBLE
#endif
#ifdef SAVER_NAVIGATIONMODEL
#undef SAVER_NAVIGATIONMODEL
#endif
#ifdef SAVER_OUTOFMEMORY
#undef SAVER_OUTOFMEMORY
#endif
#ifdef SAVER_GRAPHICS
#undef SAVER_GRAPHICS
#endif
#ifdef SAVER_NAVSERVERTIMEOUT
#undef SAVER_NAVSERVERTIMEOUT
#endif
#ifdef SAVER_CHROMEPROCESSCRASH
#undef SAVER_CHROMEPROCESSCRASH
#endif
#ifdef SAVER_NOTIFICATIONDISMISSAL
#undef SAVER_NOTIFICATIONDISMISSAL
#endif
#ifdef SAVER_SPEECHDISMISSAL
#undef SAVER_SPEECHDISMISSAL
#endif
#ifdef SAVER_CALLDISMISSAL
#undef SAVER_CALLDISMISSAL
#endif
#ifdef SAVER_APPBARDISMISSAL
#undef SAVER_APPBARDISMISSAL
#endif
#ifdef SAVER_RILADAPTATIONCRASH
#undef SAVER_RILADAPTATIONCRASH
#endif
#ifdef SAVER_APPLISTUNREACHABLE
#undef SAVER_APPLISTUNREACHABLE
#endif
#ifdef SAVER_REPORTNOTIFICATIONFAILURE
#undef SAVER_REPORTNOTIFICATIONFAILURE
#endif
#ifdef SAVER_UNEXPECTEDSHUTDOWN
#undef SAVER_UNEXPECTEDSHUTDOWN
#endif
#ifdef SAVER_RPCFAILURE
#undef SAVER_RPCFAILURE
#endif
#ifdef SAVER_AUXILIARYFULLDUMP
#undef SAVER_AUXILIARYFULLDUMP
#endif
#ifdef SAVER_ACCOUNTPROVSVCINITFAILURE
#undef SAVER_ACCOUNTPROVSVCINITFAILURE
#endif
#ifdef SAVER_MTBFCOMMANDHANG
#undef SAVER_MTBFCOMMANDHANG
#endif
#ifdef SAVER_MTBFPASSBUGCHECK
#undef SAVER_MTBFPASSBUGCHECK
#endif
#ifdef SAVER_MTBFIOERROR
#undef SAVER_MTBFIOERROR
#endif
#ifdef SAVER_RENDERTHREADHANG
#undef SAVER_RENDERTHREADHANG
#endif
#ifdef SAVER_RENDERMOBILEUIOOM
#undef SAVER_RENDERMOBILEUIOOM
#endif
#ifdef SAVER_DEVICEUPDATEUNSPECIFIED
#undef SAVER_DEVICEUPDATEUNSPECIFIED
#endif
#ifdef SAVER_AUDIODRIVERHANG
#undef SAVER_AUDIODRIVERHANG
#endif
#ifdef SAVER_BATTERYPULLOUT
#undef SAVER_BATTERYPULLOUT
#endif
#ifdef SAVER_MEDIACORETESTHANG
#undef SAVER_MEDIACORETESTHANG
#endif
#ifdef SAVER_RESOURCEMANAGEMENT
#undef SAVER_RESOURCEMANAGEMENT
#endif
#ifdef SAVER_CAPTURESERVICE
#undef SAVER_CAPTURESERVICE
#endif
#ifdef SAVER_WAITFORSHELLREADY
#undef SAVER_WAITFORSHELLREADY
#endif
#ifdef HYPERVISOR_ERROR
#undef HYPERVISOR_ERROR
#endif
#ifdef SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M
#undef SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M
#endif
#ifdef UNEXPECTED_KERNEL_MODE_TRAP_M
#undef UNEXPECTED_KERNEL_MODE_TRAP_M
#endif
#ifdef KERNEL_MODE_EXCEPTION_NOT_HANDLED_M
#undef KERNEL_MODE_EXCEPTION_NOT_HANDLED_M
#endif
#ifdef THREAD_STUCK_IN_DEVICE_DRIVER_M
#undef THREAD_STUCK_IN_DEVICE_DRIVER_M
#endif
#ifdef WINDOWS_NT_BANNER
#undef WINDOWS_NT_BANNER
#endif
#ifdef BUGCHECK_MESSAGE_INTRO
#undef BUGCHECK_MESSAGE_INTRO
#endif
#ifdef BUGCHECK_TECH_INFO
#undef BUGCHECK_TECH_INFO
#endif
#ifdef WINDOWS_NT_CSD_STRING
#undef WINDOWS_NT_CSD_STRING
#endif
#ifdef WINDOWS_NT_INFO_STRING
#undef WINDOWS_NT_INFO_STRING
#endif
#ifdef WINDOWS_NT_MP_STRING
#undef WINDOWS_NT_MP_STRING
#endif
#ifdef THREAD_TERMINATE_HELD_MUTEX
#undef THREAD_TERMINATE_HELD_MUTEX
#endif
#ifdef BUGCODE_PSS_CRASH_INIT
#undef BUGCODE_PSS_CRASH_INIT
#endif
#ifdef BUGCODE_PSS_CRASH_PROGRESS
#undef BUGCODE_PSS_CRASH_PROGRESS
#endif
#ifdef BUGCODE_PSS_CRASH_DONE
#undef BUGCODE_PSS_CRASH_DONE
#endif
#ifdef WINDOWS_NT_INFO_STRING_PLURAL
#undef WINDOWS_NT_INFO_STRING_PLURAL
#endif
#ifdef WINDOWS_NT_RC_STRING
#undef WINDOWS_NT_RC_STRING
#endif
#ifdef VIDEO_DRIVER_DEBUG_REPORT_REQUEST
#undef VIDEO_DRIVER_DEBUG_REPORT_REQUEST
#endif
#ifdef HARDWARE_PROFILE_UNDOCKED_STRING
#undef HARDWARE_PROFILE_UNDOCKED_STRING
#endif
#ifdef HARDWARE_PROFILE_DOCKED_STRING
#undef HARDWARE_PROFILE_DOCKED_STRING
#endif
#ifdef HARDWARE_PROFILE_UNKNOWN_STRING
#undef HARDWARE_PROFILE_UNKNOWN_STRING
#endif
#ifdef WINLOGON_FATAL_ERROR
#undef WINLOGON_FATAL_ERROR
#endif
#ifdef MANUALLY_INITIATED_CRASH1
#undef MANUALLY_INITIATED_CRASH1
#endif
#endif  // #if AS_UNDEF_VALUES

enum AS_DEFINE_NAME(BUG_CHECK)
{
  AS_DEFINE_NAME(APC_INDEX_MISMATCH) = 0x00000001,
  AS_DEFINE_NAME(DEVICE_QUEUE_NOT_BUSY) = 0x00000002,
  AS_DEFINE_NAME(INVALID_AFFINITY_SET) = 0x00000003,
  AS_DEFINE_NAME(INVALID_DATA_ACCESS_TRAP) = 0x00000004,
  AS_DEFINE_NAME(INVALID_PROCESS_ATTACH_ATTEMPT) = 0x00000005,
  AS_DEFINE_NAME(INVALID_PROCESS_DETACH_ATTEMPT) = 0x00000006,
  AS_DEFINE_NAME(INVALID_SOFTWARE_INTERRUPT) = 0x00000007,
  AS_DEFINE_NAME(IRQL_NOT_DISPATCH_LEVEL) = 0x00000008,
  AS_DEFINE_NAME(IRQL_NOT_GREATER_OR_EQUAL) = 0x00000009,
  AS_DEFINE_NAME(IRQL_NOT_LESS_OR_EQUAL) = 0x0000000A,
  AS_DEFINE_NAME(NO_EXCEPTION_HANDLING_SUPPORT) = 0x0000000B,
  AS_DEFINE_NAME(MAXIMUM_WAIT_OBJECTS_EXCEEDED) = 0x0000000C,
  AS_DEFINE_NAME(MUTEX_LEVEL_NUMBER_VIOLATION) = 0x0000000D,
  AS_DEFINE_NAME(NO_USER_MODE_CONTEXT) = 0x0000000E,
  AS_DEFINE_NAME(SPIN_LOCK_ALREADY_OWNED) = 0x0000000F,
  AS_DEFINE_NAME(SPIN_LOCK_NOT_OWNED) = 0x00000010,
  AS_DEFINE_NAME(THREAD_NOT_MUTEX_OWNER) = 0x00000011,
  AS_DEFINE_NAME(TRAP_CAUSE_UNKNOWN) = 0x00000012,
  AS_DEFINE_NAME(EMPTY_THREAD_REAPER_LIST) = 0x00000013,
  AS_DEFINE_NAME(CREATE_DELETE_LOCK_NOT_LOCKED) = 0x00000014,
  AS_DEFINE_NAME(LAST_CHANCE_CALLED_FROM_KMODE) = 0x00000015,
  AS_DEFINE_NAME(CID_HANDLE_CREATION) = 0x00000016,
  AS_DEFINE_NAME(CID_HANDLE_DELETION) = 0x00000017,
  AS_DEFINE_NAME(REFERENCE_BY_POINTER) = 0x00000018,
  AS_DEFINE_NAME(BAD_POOL_HEADER) = 0x00000019,
  AS_DEFINE_NAME(MEMORY_MANAGEMENT) = 0x0000001A,
  AS_DEFINE_NAME(PFN_SHARE_COUNT) = 0x0000001B,
  AS_DEFINE_NAME(PFN_REFERENCE_COUNT) = 0x0000001C,
  AS_DEFINE_NAME(NO_SPIN_LOCK_AVAILABLE) = 0x0000001D,
  AS_DEFINE_NAME(KMODE_EXCEPTION_NOT_HANDLED) = 0x0000001E,
  AS_DEFINE_NAME(SHARED_RESOURCE_CONV_ERROR) = 0x0000001F,
  AS_DEFINE_NAME(KERNEL_APC_PENDING_DURING_EXIT) = 0x00000020,
  AS_DEFINE_NAME(QUOTA_UNDERFLOW) = 0x00000021,
  AS_DEFINE_NAME(FILE_SYSTEM) = 0x00000022,
  AS_DEFINE_NAME(FAT_FILE_SYSTEM) = 0x00000023,
  AS_DEFINE_NAME(NTFS_FILE_SYSTEM) = 0x00000024,
  AS_DEFINE_NAME(NPFS_FILE_SYSTEM) = 0x00000025,
  AS_DEFINE_NAME(CDFS_FILE_SYSTEM) = 0x00000026,
  AS_DEFINE_NAME(RDR_FILE_SYSTEM) = 0x00000027,
  AS_DEFINE_NAME(CORRUPT_ACCESS_TOKEN) = 0x00000028,
  AS_DEFINE_NAME(SECURITY_SYSTEM) = 0x00000029,
  AS_DEFINE_NAME(INCONSISTENT_IRP) = 0x0000002A,
  AS_DEFINE_NAME(PANIC_STACK_SWITCH) = 0x0000002B,
  AS_DEFINE_NAME(PORT_DRIVER_INTERNAL) = 0x0000002C,
  AS_DEFINE_NAME(SCSI_DISK_DRIVER_INTERNAL) = 0x0000002D,
  AS_DEFINE_NAME(DATA_BUS_ERROR) = 0x0000002E,
  AS_DEFINE_NAME(INSTRUCTION_BUS_ERROR) = 0x0000002F,
  AS_DEFINE_NAME(SET_OF_INVALID_CONTEXT) = 0x00000030,
  AS_DEFINE_NAME(PHASE0_INITIALIZATION_FAILED) = 0x00000031,
  AS_DEFINE_NAME(PHASE1_INITIALIZATION_FAILED) = 0x00000032,
  AS_DEFINE_NAME(UNEXPECTED_INITIALIZATION_CALL) = 0x00000033,
  AS_DEFINE_NAME(CACHE_MANAGER) = 0x00000034,
  AS_DEFINE_NAME(NO_MORE_IRP_STACK_LOCATIONS) = 0x00000035,
  AS_DEFINE_NAME(DEVICE_REFERENCE_COUNT_NOT_ZERO) = 0x00000036,
  AS_DEFINE_NAME(FLOPPY_INTERNAL_ERROR) = 0x00000037,
  AS_DEFINE_NAME(SERIAL_DRIVER_INTERNAL) = 0x00000038,
  AS_DEFINE_NAME(SYSTEM_EXIT_OWNED_MUTEX) = 0x00000039,
  AS_DEFINE_NAME(SYSTEM_UNWIND_PREVIOUS_USER) = 0x0000003A,
  AS_DEFINE_NAME(SYSTEM_SERVICE_EXCEPTION) = 0x0000003B,
  AS_DEFINE_NAME(INTERRUPT_UNWIND_ATTEMPTED) = 0x0000003C,
  AS_DEFINE_NAME(INTERRUPT_EXCEPTION_NOT_HANDLED) = 0x0000003D,
  AS_DEFINE_NAME(MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED) = 0x0000003E,
  AS_DEFINE_NAME(NO_MORE_SYSTEM_PTES) = 0x0000003F,
  AS_DEFINE_NAME(TARGET_MDL_TOO_SMALL) = 0x00000040,
  AS_DEFINE_NAME(MUST_SUCCEED_POOL_EMPTY) = 0x00000041,
  AS_DEFINE_NAME(ATDISK_DRIVER_INTERNAL) = 0x00000042,
  AS_DEFINE_NAME(NO_SUCH_PARTITION) = 0x00000043,
  AS_DEFINE_NAME(MULTIPLE_IRP_COMPLETE_REQUESTS) = 0x00000044,
  AS_DEFINE_NAME(INSUFFICIENT_SYSTEM_MAP_REGS) = 0x00000045,
  AS_DEFINE_NAME(DEREF_UNKNOWN_LOGON_SESSION) = 0x00000046,
  AS_DEFINE_NAME(REF_UNKNOWN_LOGON_SESSION) = 0x00000047,
  AS_DEFINE_NAME(CANCEL_STATE_IN_COMPLETED_IRP) = 0x00000048,
  AS_DEFINE_NAME(PAGE_FAULT_WITH_INTERRUPTS_OFF) = 0x00000049,
  AS_DEFINE_NAME(IRQL_GT_ZERO_AT_SYSTEM_SERVICE) = 0x0000004A,
  AS_DEFINE_NAME(STREAMS_INTERNAL_ERROR) = 0x0000004B,
  AS_DEFINE_NAME(FATAL_UNHANDLED_HARD_ERROR) = 0x0000004C,
  AS_DEFINE_NAME(NO_PAGES_AVAILABLE) = 0x0000004D,
  AS_DEFINE_NAME(PFN_LIST_CORRUPT) = 0x0000004E,
  AS_DEFINE_NAME(NDIS_INTERNAL_ERROR) = 0x0000004F,
  AS_DEFINE_NAME(PAGE_FAULT_IN_NONPAGED_AREA) = 0x00000050,
  AS_DEFINE_NAME(REGISTRY_ERROR) = 0x00000051,
  AS_DEFINE_NAME(MAILSLOT_FILE_SYSTEM) = 0x00000052,
  AS_DEFINE_NAME(NO_BOOT_DEVICE) = 0x00000053,
  AS_DEFINE_NAME(LM_SERVER_INTERNAL_ERROR) = 0x00000054,
  AS_DEFINE_NAME(DATA_COHERENCY_EXCEPTION) = 0x00000055,
  AS_DEFINE_NAME(INSTRUCTION_COHERENCY_EXCEPTION) = 0x00000056,
  AS_DEFINE_NAME(XNS_INTERNAL_ERROR) = 0x00000057,
  AS_DEFINE_NAME(FTDISK_INTERNAL_ERROR) = 0x00000058,
  AS_DEFINE_NAME(VOLMGRX_INTERNAL_ERROR) = 0x00000058,
  AS_DEFINE_NAME(PINBALL_FILE_SYSTEM) = 0x00000059,
  AS_DEFINE_NAME(CRITICAL_SERVICE_FAILED) = 0x0000005A,
  AS_DEFINE_NAME(SET_ENV_VAR_FAILED) = 0x0000005B,
  AS_DEFINE_NAME(HAL_INITIALIZATION_FAILED) = 0x0000005C,
  AS_DEFINE_NAME(UNSUPPORTED_PROCESSOR) = 0x0000005D,
  AS_DEFINE_NAME(OBJECT_INITIALIZATION_FAILED) = 0x0000005E,
  AS_DEFINE_NAME(SECURITY_INITIALIZATION_FAILED) = 0x0000005F,
  AS_DEFINE_NAME(PROCESS_INITIALIZATION_FAILED) = 0x00000060,
  AS_DEFINE_NAME(HAL1_INITIALIZATION_FAILED) = 0x00000061,
  AS_DEFINE_NAME(OBJECT1_INITIALIZATION_FAILED) = 0x00000062,
  AS_DEFINE_NAME(SECURITY1_INITIALIZATION_FAILED) = 0x00000063,
  AS_DEFINE_NAME(SYMBOLIC_INITIALIZATION_FAILED) = 0x00000064,
  AS_DEFINE_NAME(MEMORY1_INITIALIZATION_FAILED) = 0x00000065,
  AS_DEFINE_NAME(CACHE_INITIALIZATION_FAILED) = 0x00000066,
  AS_DEFINE_NAME(CONFIG_INITIALIZATION_FAILED) = 0x00000067,
  AS_DEFINE_NAME(FILE_INITIALIZATION_FAILED) = 0x00000068,
  AS_DEFINE_NAME(IO1_INITIALIZATION_FAILED) = 0x00000069,
  AS_DEFINE_NAME(LPC_INITIALIZATION_FAILED) = 0x0000006A,
  AS_DEFINE_NAME(PROCESS1_INITIALIZATION_FAILED) = 0x0000006B,
  AS_DEFINE_NAME(REFMON_INITIALIZATION_FAILED) = 0x0000006C,
  AS_DEFINE_NAME(SESSION1_INITIALIZATION_FAILED) = 0x0000006D,
  AS_DEFINE_NAME(SESSION2_INITIALIZATION_FAILED) = 0x0000006E,
  AS_DEFINE_NAME(BOOTPROC_INITIALIZATION_FAILED) = 0x0000006E,
  AS_DEFINE_NAME(SESSION3_INITIALIZATION_FAILED) = 0x0000006F,
  AS_DEFINE_NAME(VSL_INITIALIZATION_FAILED) = 0x0000006F,
  AS_DEFINE_NAME(SESSION4_INITIALIZATION_FAILED) = 0x00000070,
  AS_DEFINE_NAME(SOFT_RESTART_FATAL_ERROR) = 0x00000070,
  AS_DEFINE_NAME(SESSION5_INITIALIZATION_FAILED) = 0x00000071,
  AS_DEFINE_NAME(ASSIGN_DRIVE_LETTERS_FAILED) = 0x00000072,
  AS_DEFINE_NAME(CONFIG_LIST_FAILED) = 0x00000073,
  AS_DEFINE_NAME(BAD_SYSTEM_CONFIG_INFO) = 0x00000074,
  AS_DEFINE_NAME(CANNOT_WRITE_CONFIGURATION) = 0x00000075,
  AS_DEFINE_NAME(PROCESS_HAS_LOCKED_PAGES) = 0x00000076,
  AS_DEFINE_NAME(KERNEL_STACK_INPAGE_ERROR) = 0x00000077,
  AS_DEFINE_NAME(PHASE0_EXCEPTION) = 0x00000078,
  AS_DEFINE_NAME(MISMATCHED_HAL) = 0x00000079,
  AS_DEFINE_NAME(KERNEL_DATA_INPAGE_ERROR) = 0x0000007A,
  AS_DEFINE_NAME(INACCESSIBLE_BOOT_DEVICE) = 0x0000007B,
  AS_DEFINE_NAME(BUGCODE_NDIS_DRIVER) = 0x0000007C,
  AS_DEFINE_NAME(INSTALL_MORE_MEMORY) = 0x0000007D,
  AS_DEFINE_NAME(SYSTEM_THREAD_EXCEPTION_NOT_HANDLED) = 0x0000007E,
  AS_DEFINE_NAME(UNEXPECTED_KERNEL_MODE_TRAP) = 0x0000007F,
  AS_DEFINE_NAME(NMI_HARDWARE_FAILURE) = 0x00000080,
  AS_DEFINE_NAME(SPIN_LOCK_INIT_FAILURE) = 0x00000081,
  AS_DEFINE_NAME(DFS_FILE_SYSTEM) = 0x00000082,
  AS_DEFINE_NAME(OFS_FILE_SYSTEM) = 0x00000083,
  AS_DEFINE_NAME(RECOM_DRIVER) = 0x00000084,
  AS_DEFINE_NAME(SETUP_FAILURE) = 0x00000085,
  AS_DEFINE_NAME(AUDIT_FAILURE) = 0x00000086,
  AS_DEFINE_NAME(MBR_CHECKSUM_MISMATCH) = 0x0000008B,
  AS_DEFINE_NAME(KERNEL_MODE_EXCEPTION_NOT_HANDLED) = 0x0000008E,
  AS_DEFINE_NAME(PP0_INITIALIZATION_FAILED) = 0x0000008F,
  AS_DEFINE_NAME(PP1_INITIALIZATION_FAILED) = 0x00000090,
  AS_DEFINE_NAME(WIN32K_INIT_OR_RIT_FAILURE) = 0x00000091,
  AS_DEFINE_NAME(UP_DRIVER_ON_MP_SYSTEM) = 0x00000092,
  AS_DEFINE_NAME(INVALID_KERNEL_HANDLE) = 0x00000093,
  AS_DEFINE_NAME(KERNEL_STACK_LOCKED_AT_EXIT) = 0x00000094,
  AS_DEFINE_NAME(PNP_INTERNAL_ERROR) = 0x00000095,
  AS_DEFINE_NAME(INVALID_WORK_QUEUE_ITEM) = 0x00000096,
  AS_DEFINE_NAME(BOUND_IMAGE_UNSUPPORTED) = 0x00000097,
  AS_DEFINE_NAME(END_OF_NT_EVALUATION_PERIOD) = 0x00000098,
  AS_DEFINE_NAME(INVALID_REGION_OR_SEGMENT) = 0x00000099,
  AS_DEFINE_NAME(SYSTEM_LICENSE_VIOLATION) = 0x0000009A,
  AS_DEFINE_NAME(UDFS_FILE_SYSTEM) = 0x0000009B,
  AS_DEFINE_NAME(MACHINE_CHECK_EXCEPTION) = 0x0000009C,
  AS_DEFINE_NAME(USER_MODE_HEALTH_MONITOR) = 0x0000009E,
  AS_DEFINE_NAME(DRIVER_POWER_STATE_FAILURE) = 0x0000009F,
  AS_DEFINE_NAME(INTERNAL_POWER_ERROR) = 0x000000A0,
  AS_DEFINE_NAME(PCI_BUS_DRIVER_INTERNAL) = 0x000000A1,
  AS_DEFINE_NAME(MEMORY_IMAGE_CORRUPT) = 0x000000A2,
  AS_DEFINE_NAME(ACPI_DRIVER_INTERNAL) = 0x000000A3,
  AS_DEFINE_NAME(CNSS_FILE_SYSTEM_FILTER) = 0x000000A4,
  AS_DEFINE_NAME(ACPI_BIOS_ERROR) = 0x000000A5,
  AS_DEFINE_NAME(FP_EMULATION_ERROR) = 0x000000A6,
  AS_DEFINE_NAME(BAD_EXHANDLE) = 0x000000A7,
  AS_DEFINE_NAME(BOOTING_IN_SAFEMODE_MINIMAL) = 0x000000A8,
  AS_DEFINE_NAME(BOOTING_IN_SAFEMODE_NETWORK) = 0x000000A9,
  AS_DEFINE_NAME(BOOTING_IN_SAFEMODE_DSREPAIR) = 0x000000AA,
  AS_DEFINE_NAME(SESSION_HAS_VALID_POOL_ON_EXIT) = 0x000000AB,
  AS_DEFINE_NAME(HAL_MEMORY_ALLOCATION) = 0x000000AC,
  AS_DEFINE_NAME(BGI_DETECTED_VIOLATION) = 0x000000B1,
  AS_DEFINE_NAME(VIDEO_DRIVER_INIT_FAILURE) = 0x000000B4,
  AS_DEFINE_NAME(BOOTLOG_LOADED) = 0x000000B5,
  AS_DEFINE_NAME(BOOTLOG_NOT_LOADED) = 0x000000B6,
  AS_DEFINE_NAME(BOOTLOG_ENABLED) = 0x000000B7,
  AS_DEFINE_NAME(ATTEMPTED_SWITCH_FROM_DPC) = 0x000000B8,
  AS_DEFINE_NAME(CHIPSET_DETECTED_ERROR) = 0x000000B9,
  AS_DEFINE_NAME(SESSION_HAS_VALID_VIEWS_ON_EXIT) = 0x000000BA,
  AS_DEFINE_NAME(NETWORK_BOOT_INITIALIZATION_FAILED) = 0x000000BB,
  AS_DEFINE_NAME(NETWORK_BOOT_DUPLICATE_ADDRESS) = 0x000000BC,
  AS_DEFINE_NAME(INVALID_HIBERNATED_STATE) = 0x000000BD,
  AS_DEFINE_NAME(ATTEMPTED_WRITE_TO_READONLY_MEMORY) = 0x000000BE,
  AS_DEFINE_NAME(MUTEX_ALREADY_OWNED) = 0x000000BF,
  AS_DEFINE_NAME(PCI_CONFIG_SPACE_ACCESS_FAILURE) = 0x000000C0,
  AS_DEFINE_NAME(SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION) = 0x000000C1,
  AS_DEFINE_NAME(BAD_POOL_CALLER) = 0x000000C2,
  AS_DEFINE_NAME(SYSTEM_IMAGE_BAD_SIGNATURE) = 0x000000C3,
  AS_DEFINE_NAME(DRIVER_VERIFIER_DETECTED_VIOLATION) = 0x000000C4,
  AS_DEFINE_NAME(DRIVER_CORRUPTED_EXPOOL) = 0x000000C5,
  AS_DEFINE_NAME(DRIVER_CAUGHT_MODIFYING_FREED_POOL) = 0x000000C6,
  AS_DEFINE_NAME(TIMER_OR_DPC_INVALID) = 0x000000C7,
  AS_DEFINE_NAME(IRQL_UNEXPECTED_VALUE) = 0x000000C8,
  AS_DEFINE_NAME(DRIVER_VERIFIER_IOMANAGER_VIOLATION) = 0x000000C9,
  AS_DEFINE_NAME(PNP_DETECTED_FATAL_ERROR) = 0x000000CA,
  AS_DEFINE_NAME(DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS) = 0x000000CB,
  AS_DEFINE_NAME(PAGE_FAULT_IN_FREED_SPECIAL_POOL) = 0x000000CC,
  AS_DEFINE_NAME(PAGE_FAULT_BEYOND_END_OF_ALLOCATION) = 0x000000CD,
  AS_DEFINE_NAME(DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS) = 0x000000CE,
  AS_DEFINE_NAME(TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE) = 0x000000CF,
  AS_DEFINE_NAME(DRIVER_CORRUPTED_MMPOOL) = 0x000000D0,
  AS_DEFINE_NAME(DRIVER_IRQL_NOT_LESS_OR_EQUAL) = 0x000000D1,
  AS_DEFINE_NAME(BUGCODE_ID_DRIVER) = 0x000000D2,
  AS_DEFINE_NAME(DRIVER_PORTION_MUST_BE_NONPAGED) = 0x000000D3,
  AS_DEFINE_NAME(SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD) = 0x000000D4,
  AS_DEFINE_NAME(DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL) = 0x000000D5,
  AS_DEFINE_NAME(DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION) = 0x000000D6,
  AS_DEFINE_NAME(DRIVER_UNMAPPING_INVALID_VIEW) = 0x000000D7,
  AS_DEFINE_NAME(DRIVER_USED_EXCESSIVE_PTES) = 0x000000D8,
  AS_DEFINE_NAME(LOCKED_PAGES_TRACKER_CORRUPTION) = 0x000000D9,
  AS_DEFINE_NAME(SYSTEM_PTE_MISUSE) = 0x000000DA,
  AS_DEFINE_NAME(DRIVER_CORRUPTED_SYSPTES) = 0x000000DB,
  AS_DEFINE_NAME(DRIVER_INVALID_STACK_ACCESS) = 0x000000DC,
  AS_DEFINE_NAME(POOL_CORRUPTION_IN_FILE_AREA) = 0x000000DE,
  AS_DEFINE_NAME(IMPERSONATING_WORKER_THREAD) = 0x000000DF,
  AS_DEFINE_NAME(ACPI_BIOS_FATAL_ERROR) = 0x000000E0,
  AS_DEFINE_NAME(WORKER_THREAD_RETURNED_AT_BAD_IRQL) = 0x000000E1,
  AS_DEFINE_NAME(MANUALLY_INITIATED_CRASH) = 0x000000E2,
  AS_DEFINE_NAME(RESOURCE_NOT_OWNED) = 0x000000E3,
  AS_DEFINE_NAME(WORKER_INVALID) = 0x000000E4,
  AS_DEFINE_NAME(POWER_FAILURE_SIMULATE) = 0x000000E5,
  AS_DEFINE_NAME(DRIVER_VERIFIER_DMA_VIOLATION) = 0x000000E6,
  AS_DEFINE_NAME(INVALID_FLOATING_POINT_STATE) = 0x000000E7,
  AS_DEFINE_NAME(INVALID_CANCEL_OF_FILE_OPEN) = 0x000000E8,
  AS_DEFINE_NAME(ACTIVE_EX_WORKER_THREAD_TERMINATION) = 0x000000E9,
  AS_DEFINE_NAME(THREAD_STUCK_IN_DEVICE_DRIVER) = 0x000000EA,
  AS_DEFINE_NAME(DIRTY_MAPPED_PAGES_CONGESTION) = 0x000000EB,
  AS_DEFINE_NAME(SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT) = 0x000000EC,
  AS_DEFINE_NAME(UNMOUNTABLE_BOOT_VOLUME) = 0x000000ED,
  AS_DEFINE_NAME(CRITICAL_PROCESS_DIED) = 0x000000EF,
  AS_DEFINE_NAME(STORAGE_MINIPORT_ERROR) = 0x000000F0,
  AS_DEFINE_NAME(SCSI_VERIFIER_DETECTED_VIOLATION) = 0x000000F1,
  AS_DEFINE_NAME(HARDWARE_INTERRUPT_STORM) = 0x000000F2,
  AS_DEFINE_NAME(DISORDERLY_SHUTDOWN) = 0x000000F3,
  AS_DEFINE_NAME(CRITICAL_OBJECT_TERMINATION) = 0x000000F4,
  AS_DEFINE_NAME(FLTMGR_FILE_SYSTEM) = 0x000000F5,
  AS_DEFINE_NAME(PCI_VERIFIER_DETECTED_VIOLATION) = 0x000000F6,
  AS_DEFINE_NAME(DRIVER_OVERRAN_STACK_BUFFER) = 0x000000F7,
  AS_DEFINE_NAME(RAMDISK_BOOT_INITIALIZATION_FAILED) = 0x000000F8,
  AS_DEFINE_NAME(DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN) = 0x000000F9,
  AS_DEFINE_NAME(HTTP_DRIVER_CORRUPTED) = 0x000000FA,
  AS_DEFINE_NAME(RECURSIVE_MACHINE_CHECK) = 0x000000FB,
  AS_DEFINE_NAME(ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY) = 0x000000FC,
  AS_DEFINE_NAME(DIRTY_NOWRITE_PAGES_CONGESTION) = 0x000000FD,
  AS_DEFINE_NAME(BUGCODE_USB_DRIVER) = 0x000000FE,
  AS_DEFINE_NAME(RESERVE_QUEUE_OVERFLOW) = 0x000000FF,
  AS_DEFINE_NAME(LOADER_BLOCK_MISMATCH) = 0x00000100,
  AS_DEFINE_NAME(CLOCK_WATCHDOG_TIMEOUT) = 0x00000101,
  AS_DEFINE_NAME(DPC_WATCHDOG_TIMEOUT) = 0x00000102,
  AS_DEFINE_NAME(MUP_FILE_SYSTEM) = 0x00000103,
  AS_DEFINE_NAME(AGP_INVALID_ACCESS) = 0x00000104,
  AS_DEFINE_NAME(AGP_GART_CORRUPTION) = 0x00000105,
  AS_DEFINE_NAME(AGP_ILLEGALLY_REPROGRAMMED) = 0x00000106,
  AS_DEFINE_NAME(KERNEL_EXPAND_STACK_ACTIVE) = 0x00000107,
  AS_DEFINE_NAME(THIRD_PARTY_FILE_SYSTEM_FAILURE) = 0x00000108,
  AS_DEFINE_NAME(CRITICAL_STRUCTURE_CORRUPTION) = 0x00000109,
  AS_DEFINE_NAME(APP_TAGGING_INITIALIZATION_FAILED) = 0x0000010A,
  AS_DEFINE_NAME(DFSC_FILE_SYSTEM) = 0x0000010B,
  AS_DEFINE_NAME(FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION) = 0x0000010C,
  AS_DEFINE_NAME(WDF_VIOLATION) = 0x0000010D,
  AS_DEFINE_NAME(VIDEO_MEMORY_MANAGEMENT_INTERNAL) = 0x0000010E,
  AS_DEFINE_NAME(DRIVER_INVALID_CRUNTIME_PARAMETER) = 0x00000110,
  AS_DEFINE_NAME(RECURSIVE_NMI) = 0x00000111,
  AS_DEFINE_NAME(MSRPC_STATE_VIOLATION) = 0x00000112,
  AS_DEFINE_NAME(VIDEO_DXGKRNL_FATAL_ERROR) = 0x00000113,
  AS_DEFINE_NAME(VIDEO_SHADOW_DRIVER_FATAL_ERROR) = 0x00000114,
  AS_DEFINE_NAME(AGP_INTERNAL) = 0x00000115,
  AS_DEFINE_NAME(VIDEO_TDR_FAILURE) = 0x00000116,
  AS_DEFINE_NAME(VIDEO_TDR_TIMEOUT_DETECTED) = 0x00000117,
  AS_DEFINE_NAME(NTHV_GUEST_ERROR) = 0x00000118,
  AS_DEFINE_NAME(VIDEO_SCHEDULER_INTERNAL_ERROR) = 0x00000119,
  AS_DEFINE_NAME(EM_INITIALIZATION_ERROR) = 0x0000011A,
  AS_DEFINE_NAME(DRIVER_RETURNED_HOLDING_CANCEL_LOCK) = 0x0000011B,
  AS_DEFINE_NAME(ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE) = 0x0000011C,
  AS_DEFINE_NAME(EVENT_TRACING_FATAL_ERROR) = 0x0000011D,
  AS_DEFINE_NAME(TOO_MANY_RECURSIVE_FAULTS) = 0x0000011E,
  AS_DEFINE_NAME(INVALID_DRIVER_HANDLE) = 0x0000011F,
  AS_DEFINE_NAME(BITLOCKER_FATAL_ERROR) = 0x00000120,
  AS_DEFINE_NAME(DRIVER_VIOLATION) = 0x00000121,
  AS_DEFINE_NAME(WHEA_INTERNAL_ERROR) = 0x00000122,
  AS_DEFINE_NAME(CRYPTO_SELF_TEST_FAILURE) = 0x00000123,
  AS_DEFINE_NAME(WHEA_UNCORRECTABLE_ERROR) = 0x00000124,
  AS_DEFINE_NAME(NMR_INVALID_STATE) = 0x00000125,
  AS_DEFINE_NAME(NETIO_INVALID_POOL_CALLER) = 0x00000126,
  AS_DEFINE_NAME(PAGE_NOT_ZERO) = 0x00000127,
  AS_DEFINE_NAME(WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY) = 0x00000128,
  AS_DEFINE_NAME(WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY) = 0x00000129,
  AS_DEFINE_NAME(MUI_NO_VALID_SYSTEM_LANGUAGE) = 0x0000012A,
  AS_DEFINE_NAME(FAULTY_HARDWARE_CORRUPTED_PAGE) = 0x0000012B,
  AS_DEFINE_NAME(EXFAT_FILE_SYSTEM) = 0x0000012C,
  AS_DEFINE_NAME(VOLSNAP_OVERLAPPED_TABLE_ACCESS) = 0x0000012D,
  AS_DEFINE_NAME(INVALID_MDL_RANGE) = 0x0000012E,
  AS_DEFINE_NAME(VHD_BOOT_INITIALIZATION_FAILED) = 0x0000012F,
  AS_DEFINE_NAME(DYNAMIC_ADD_PROCESSOR_MISMATCH) = 0x00000130,
  AS_DEFINE_NAME(INVALID_EXTENDED_PROCESSOR_STATE) = 0x00000131,
  AS_DEFINE_NAME(RESOURCE_OWNER_POINTER_INVALID) = 0x00000132,
  AS_DEFINE_NAME(DPC_WATCHDOG_VIOLATION) = 0x00000133,
  AS_DEFINE_NAME(DRIVE_EXTENDER) = 0x00000134,
  AS_DEFINE_NAME(REGISTRY_FILTER_DRIVER_EXCEPTION) = 0x00000135,
  AS_DEFINE_NAME(VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE) = 0x00000136,
  AS_DEFINE_NAME(WIN32K_HANDLE_MANAGER) = 0x00000137,
  AS_DEFINE_NAME(GPIO_CONTROLLER_DRIVER_ERROR) = 0x00000138,
  AS_DEFINE_NAME(KERNEL_SECURITY_CHECK_FAILURE) = 0x00000139,
  AS_DEFINE_NAME(KERNEL_MODE_HEAP_CORRUPTION) = 0x0000013A,
  AS_DEFINE_NAME(PASSIVE_INTERRUPT_ERROR) = 0x0000013B,
  AS_DEFINE_NAME(INVALID_IO_BOOST_STATE) = 0x0000013C,
  AS_DEFINE_NAME(CRITICAL_INITIALIZATION_FAILURE) = 0x0000013D,
  AS_DEFINE_NAME(ERRATA_WORKAROUND_UNSUCCESSFUL) = 0x0000013E,
  AS_DEFINE_NAME(STORAGE_DEVICE_ABNORMALITY_DETECTED) = 0x00000140,
  AS_DEFINE_NAME(VIDEO_ENGINE_TIMEOUT_DETECTED) = 0x00000141,
  AS_DEFINE_NAME(VIDEO_TDR_APPLICATION_BLOCKED) = 0x00000142,
  AS_DEFINE_NAME(PROCESSOR_DRIVER_INTERNAL) = 0x00000143,
  AS_DEFINE_NAME(BUGCODE_USB3_DRIVER) = 0x00000144,
  AS_DEFINE_NAME(SECURE_BOOT_VIOLATION) = 0x00000145,
  AS_DEFINE_NAME(NDIS_NET_BUFFER_LIST_INFO_ILLEGALLY_TRANSFERRED) = 0x00000146,
  AS_DEFINE_NAME(ABNORMAL_RESET_DETECTED) = 0x00000147,
  AS_DEFINE_NAME(IO_OBJECT_INVALID) = 0x00000148,
  AS_DEFINE_NAME(REFS_FILE_SYSTEM) = 0x00000149,
  AS_DEFINE_NAME(KERNEL_WMI_INTERNAL) = 0x0000014A,
  AS_DEFINE_NAME(SOC_SUBSYSTEM_FAILURE) = 0x0000014B,
  AS_DEFINE_NAME(FATAL_ABNORMAL_RESET_ERROR) = 0x0000014C,
  AS_DEFINE_NAME(EXCEPTION_SCOPE_INVALID) = 0x0000014D,
  AS_DEFINE_NAME(SOC_CRITICAL_DEVICE_REMOVED) = 0x0000014E,
  AS_DEFINE_NAME(PDC_WATCHDOG_TIMEOUT) = 0x0000014F,
  AS_DEFINE_NAME(TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK) = 0x00000150,
  AS_DEFINE_NAME(UNSUPPORTED_INSTRUCTION_MODE) = 0x00000151,
  AS_DEFINE_NAME(INVALID_PUSH_LOCK_FLAGS) = 0x00000152,
  AS_DEFINE_NAME(KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION) = 0x00000153,
  AS_DEFINE_NAME(UNEXPECTED_STORE_EXCEPTION) = 0x00000154,
  AS_DEFINE_NAME(OS_DATA_TAMPERING) = 0x00000155,
  AS_DEFINE_NAME(WINSOCK_DETECTED_HUNG_CLOSESOCKET_LIVEDUMP) = 0x00000156,
  AS_DEFINE_NAME(KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION) = 0x00000157,
  AS_DEFINE_NAME(ILLEGAL_IOMMU_PAGE_FAULT) = 0x00000158,
  AS_DEFINE_NAME(HAL_ILLEGAL_IOMMU_PAGE_FAULT) = 0x00000159,
  AS_DEFINE_NAME(SDBUS_INTERNAL_ERROR) = 0x0000015A,
  AS_DEFINE_NAME(WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE) = 0x0000015B,
  AS_DEFINE_NAME(PDC_WATCHDOG_TIMEOUT_LIVEDUMP) = 0x0000015C,
  AS_DEFINE_NAME(SOC_SUBSYSTEM_FAILURE_LIVEDUMP) = 0x0000015D,
  AS_DEFINE_NAME(BUGCODE_NDIS_DRIVER_LIVE_DUMP) = 0x0000015E,
  AS_DEFINE_NAME(CONNECTED_STANDBY_WATCHDOG_TIMEOUT_LIVEDUMP) = 0x0000015F,
  AS_DEFINE_NAME(WIN32K_ATOMIC_CHECK_FAILURE) = 0x00000160,
  AS_DEFINE_NAME(LIVE_SYSTEM_DUMP) = 0x00000161,
  AS_DEFINE_NAME(KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE) = 0x00000162,
  AS_DEFINE_NAME(WORKER_THREAD_TEST_CONDITION) = 0x00000163,
  AS_DEFINE_NAME(WIN32K_CRITICAL_FAILURE) = 0x00000164,
  AS_DEFINE_NAME(CLUSTER_CSV_STATUS_IO_TIMEOUT_LIVEDUMP) = 0x00000165,
  AS_DEFINE_NAME(CLUSTER_RESOURCE_CALL_TIMEOUT_LIVEDUMP) = 0x00000166,
  AS_DEFINE_NAME(CLUSTER_CSV_SNAPSHOT_DEVICE_INFO_TIMEOUT_LIVEDUMP) = 0x00000167,
  AS_DEFINE_NAME(CLUSTER_CSV_STATE_TRANSITION_TIMEOUT_LIVEDUMP) = 0x00000168,
  AS_DEFINE_NAME(CLUSTER_CSV_VOLUME_ARRIVAL_LIVEDUMP) = 0x00000169,
  AS_DEFINE_NAME(CLUSTER_CSV_VOLUME_REMOVAL_LIVEDUMP) = 0x0000016A,
  AS_DEFINE_NAME(CLUSTER_CSV_CLUSTER_WATCHDOG_LIVEDUMP) = 0x0000016B,
  AS_DEFINE_NAME(INVALID_RUNDOWN_PROTECTION_FLAGS) = 0x0000016C,
  AS_DEFINE_NAME(INVALID_SLOT_ALLOCATOR_FLAGS) = 0x0000016D,
  AS_DEFINE_NAME(ERESOURCE_INVALID_RELEASE) = 0x0000016E,
  AS_DEFINE_NAME(CLUSTER_CSV_STATE_TRANSITION_INTERVAL_TIMEOUT_LIVEDUMP) = 0x0000016F,
  AS_DEFINE_NAME(CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG) = 0x00000170,
  AS_DEFINE_NAME(CRYPTO_LIBRARY_INTERNAL_ERROR) = 0x00000171,
  AS_DEFINE_NAME(COREMSGCALL_INTERNAL_ERROR) = 0x00000173,
  AS_DEFINE_NAME(COREMSG_INTERNAL_ERROR) = 0x00000174,
  AS_DEFINE_NAME(PREVIOUS_FATAL_ABNORMAL_RESET_ERROR) = 0x00000175,
  AS_DEFINE_NAME(ELAM_DRIVER_DETECTED_FATAL_ERROR) = 0x00000178,
  AS_DEFINE_NAME(CLUSTER_CLUSPORT_STATUS_IO_TIMEOUT_LIVEDUMP) = 0x00000179,
  AS_DEFINE_NAME(PROFILER_CONFIGURATION_ILLEGAL) = 0x0000017B,
  AS_DEFINE_NAME(PDC_LOCK_WATCHDOG_LIVEDUMP) = 0x0000017C,
  AS_DEFINE_NAME(PDC_UNEXPECTED_REVOCATION_LIVEDUMP) = 0x0000017D,
  AS_DEFINE_NAME(WVR_LIVEDUMP_REPLICATION_IOCONTEXT_TIMEOUT) = 0x00000180,
  AS_DEFINE_NAME(WVR_LIVEDUMP_STATE_TRANSITION_TIMEOUT) = 0x00000181,
  AS_DEFINE_NAME(WVR_LIVEDUMP_RECOVERY_IOCONTEXT_TIMEOUT) = 0x00000182,
  AS_DEFINE_NAME(WVR_LIVEDUMP_APP_IO_TIMEOUT) = 0x00000183,
  AS_DEFINE_NAME(WVR_LIVEDUMP_MANUALLY_INITIATED) = 0x00000184,
  AS_DEFINE_NAME(WVR_LIVEDUMP_STATE_FAILURE) = 0x00000185,
  AS_DEFINE_NAME(WVR_LIVEDUMP_CRITICAL_ERROR) = 0x00000186,
  AS_DEFINE_NAME(VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD) = 0x00000187,
  AS_DEFINE_NAME(CLUSTER_CSVFS_LIVEDUMP) = 0x00000188,
  AS_DEFINE_NAME(BAD_OBJECT_HEADER) = 0x00000189,
  AS_DEFINE_NAME(SILO_CORRUPT) = 0x0000018A,
  AS_DEFINE_NAME(SECURE_KERNEL_ERROR) = 0x0000018B,
  AS_DEFINE_NAME(HYPERGUARD_VIOLATION) = 0x0000018C,
  AS_DEFINE_NAME(SECURE_FAULT_UNHANDLED) = 0x0000018D,
  AS_DEFINE_NAME(KERNEL_PARTITION_REFERENCE_VIOLATION) = 0x0000018E,
  AS_DEFINE_NAME(WIN32K_CRITICAL_FAILURE_LIVEDUMP) = 0x00000190,
  AS_DEFINE_NAME(PF_DETECTED_CORRUPTION) = 0x00000191,
  AS_DEFINE_NAME(KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL) = 0x00000192,
  AS_DEFINE_NAME(VIDEO_DXGKRNL_LIVEDUMP) = 0x00000193,
  AS_DEFINE_NAME(SAVER_NONRESPONSIVEPROCESS) = 0x00000194,
  AS_DEFINE_NAME(SMB_SERVER_LIVEDUMP) = 0x00000195,
  AS_DEFINE_NAME(LOADER_ROLLBACK_DETECTED) = 0x00000196,
  AS_DEFINE_NAME(WIN32K_SECURITY_FAILURE) = 0x00000197,
  AS_DEFINE_NAME(UFX_LIVEDUMP) = 0x00000198,
  AS_DEFINE_NAME(KERNEL_STORAGE_SLOT_IN_USE) = 0x00000199,
  AS_DEFINE_NAME(WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO) = 0x0000019A,
  AS_DEFINE_NAME(TTM_FATAL_ERROR) = 0x0000019B,
  AS_DEFINE_NAME(WIN32K_POWER_WATCHDOG_TIMEOUT) = 0x0000019C,
  AS_DEFINE_NAME(CLUSTER_SVHDX_LIVEDUMP) = 0x0000019D,
  AS_DEFINE_NAME(BUGCODE_NETADAPTER_DRIVER) = 0x0000019E,
  AS_DEFINE_NAME(PDC_PRIVILEGE_CHECK_LIVEDUMP) = 0x0000019F,
  AS_DEFINE_NAME(TTM_WATCHDOG_TIMEOUT) = 0x000001A0,
  AS_DEFINE_NAME(WIN32K_CALLOUT_WATCHDOG_LIVEDUMP) = 0x000001A1,
  AS_DEFINE_NAME(WIN32K_CALLOUT_WATCHDOG_BUGCHECK) = 0x000001A2,
  AS_DEFINE_NAME(CALL_HAS_NOT_RETURNED_WATCHDOG_TIMEOUT_LIVEDUMP) = 0x000001A3,
  AS_DEFINE_NAME(DRIPS_SW_HW_DIVERGENCE_LIVEDUMP) = 0x000001A4,
  AS_DEFINE_NAME(USB_DRIPS_BLOCKER_SURPRISE_REMOVAL_LIVEDUMP) = 0x000001A5,
  AS_DEFINE_NAME(DRIVER_VERIFIER_DETECTED_VIOLATION_LIVEDUMP) = 0x000001C4,
  AS_DEFINE_NAME(IO_THREADPOOL_DEADLOCK_LIVEDUMP) = 0x000001C5,
  AS_DEFINE_NAME(FAST_ERESOURCE_PRECONDITION_VIOLATION) = 0x000001C6,
  AS_DEFINE_NAME(STORE_DATA_STRUCTURE_CORRUPTION) = 0x000001C7,
  AS_DEFINE_NAME(MANUALLY_INITIATED_POWER_BUTTON_HOLD) = 0x000001C8,
  AS_DEFINE_NAME(USER_MODE_HEALTH_MONITOR_LIVEDUMP) = 0x000001C9,
  AS_DEFINE_NAME(HYPERVISOR_WATCHDOG_TIMEOUT) = 0x000001CA,
  AS_DEFINE_NAME(INVALID_SILO_DETACH) = 0x000001CB,
  AS_DEFINE_NAME(EXRESOURCE_TIMEOUT_LIVEDUMP) = 0x000001CC,
  AS_DEFINE_NAME(INVALID_CALLBACK_STACK_ADDRESS) = 0x000001CD,
  AS_DEFINE_NAME(INVALID_KERNEL_STACK_ADDRESS) = 0x000001CE,
  AS_DEFINE_NAME(HARDWARE_WATCHDOG_TIMEOUT) = 0x000001CF,
  AS_DEFINE_NAME(ACPI_FIRMWARE_WATCHDOG_TIMEOUT) = 0x000001D0,
  AS_DEFINE_NAME(TELEMETRY_ASSERTS_LIVEDUMP) = 0x000001D1,
  AS_DEFINE_NAME(WORKER_THREAD_INVALID_STATE) = 0x000001D2,
  AS_DEFINE_NAME(WFP_INVALID_OPERATION) = 0x000001D3,
  AS_DEFINE_NAME(UCMUCSI_LIVEDUMP) = 0x000001D4,
  AS_DEFINE_NAME(DRIVER_PNP_WATCHDOG) = 0x000001D5,
  AS_DEFINE_NAME(SAVER_MTBFCOMMANDTIMEOUT) = 0x00000315,
  AS_DEFINE_NAME(XBOX_ERACTRL_CS_TIMEOUT) = 0x00000356,
  AS_DEFINE_NAME(XBOX_CORRUPTED_IMAGE) = 0x00000357,
  AS_DEFINE_NAME(XBOX_INVERTED_FUNCTION_TABLE_OVERFLOW) = 0x00000358,
  AS_DEFINE_NAME(XBOX_CORRUPTED_IMAGE_BASE) = 0x00000359,
  AS_DEFINE_NAME(XBOX_360_SYSTEM_CRASH) = 0x00000360,
  AS_DEFINE_NAME(XBOX_360_SYSTEM_CRASH_RESERVED) = 0x00000420,
  AS_DEFINE_NAME(BC_BLUETOOTH_VERIFIER_FAULT) = 0x00000BFE,
  AS_DEFINE_NAME(BC_BTHMINI_VERIFIER_FAULT) = 0x00000BFF,
  AS_DEFINE_NAME(SAVER_SICKAPPLICATION) = 0x00008866,
  AS_DEFINE_NAME(SAVER_UNSPECIFIED) = 0x0000F000,
  AS_DEFINE_NAME(SAVER_BLANKSCREEN) = 0x0000F002,
  AS_DEFINE_NAME(SAVER_INPUT) = 0x0000F003,
  AS_DEFINE_NAME(SAVER_WATCHDOG) = 0x0000F004,
  AS_DEFINE_NAME(SAVER_STARTNOTVISIBLE) = 0x0000F005,
  AS_DEFINE_NAME(SAVER_NAVIGATIONMODEL) = 0x0000F006,
  AS_DEFINE_NAME(SAVER_OUTOFMEMORY) = 0x0000F007,
  AS_DEFINE_NAME(SAVER_GRAPHICS) = 0x0000F008,
  AS_DEFINE_NAME(SAVER_NAVSERVERTIMEOUT) = 0x0000F009,
  AS_DEFINE_NAME(SAVER_CHROMEPROCESSCRASH) = 0x0000F00A,
  AS_DEFINE_NAME(SAVER_NOTIFICATIONDISMISSAL) = 0x0000F00B,
  AS_DEFINE_NAME(SAVER_SPEECHDISMISSAL) = 0x0000F00C,
  AS_DEFINE_NAME(SAVER_CALLDISMISSAL) = 0x0000F00D,
  AS_DEFINE_NAME(SAVER_APPBARDISMISSAL) = 0x0000F00E,
  AS_DEFINE_NAME(SAVER_RILADAPTATIONCRASH) = 0x0000F00F,
  AS_DEFINE_NAME(SAVER_APPLISTUNREACHABLE) = 0x0000F010,
  AS_DEFINE_NAME(SAVER_REPORTNOTIFICATIONFAILURE) = 0x0000F011,
  AS_DEFINE_NAME(SAVER_UNEXPECTEDSHUTDOWN) = 0x0000F012,
  AS_DEFINE_NAME(SAVER_RPCFAILURE) = 0x0000F013,
  AS_DEFINE_NAME(SAVER_AUXILIARYFULLDUMP) = 0x0000F014,
  AS_DEFINE_NAME(SAVER_ACCOUNTPROVSVCINITFAILURE) = 0x0000F015,
  AS_DEFINE_NAME(SAVER_MTBFCOMMANDHANG) = 0x0000F101,
  AS_DEFINE_NAME(SAVER_MTBFPASSBUGCHECK) = 0x0000F102,
  AS_DEFINE_NAME(SAVER_MTBFIOERROR) = 0x0000F103,
  AS_DEFINE_NAME(SAVER_RENDERTHREADHANG) = 0x0000F200,
  AS_DEFINE_NAME(SAVER_RENDERMOBILEUIOOM) = 0x0000F201,
  AS_DEFINE_NAME(SAVER_DEVICEUPDATEUNSPECIFIED) = 0x0000F300,
  AS_DEFINE_NAME(SAVER_AUDIODRIVERHANG) = 0x0000F400,
  AS_DEFINE_NAME(SAVER_BATTERYPULLOUT) = 0x0000F500,
  AS_DEFINE_NAME(SAVER_MEDIACORETESTHANG) = 0x0000F600,
  AS_DEFINE_NAME(SAVER_RESOURCEMANAGEMENT) = 0x0000F700,
  AS_DEFINE_NAME(SAVER_CAPTURESERVICE) = 0x0000F800,
  AS_DEFINE_NAME(SAVER_WAITFORSHELLREADY) = 0x0000F900,
  AS_DEFINE_NAME(HYPERVISOR_ERROR) = 0x00020001,
  AS_DEFINE_NAME(SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M) = 0x1000007E,
  AS_DEFINE_NAME(UNEXPECTED_KERNEL_MODE_TRAP_M) = 0x1000007F,
  AS_DEFINE_NAME(KERNEL_MODE_EXCEPTION_NOT_HANDLED_M) = 0x1000008E,
  AS_DEFINE_NAME(THREAD_STUCK_IN_DEVICE_DRIVER_M) = 0x100000EA,
  AS_DEFINE_NAME(WINDOWS_NT_BANNER) = 0x4000007E,
  AS_DEFINE_NAME(BUGCHECK_MESSAGE_INTRO) = 0x4000007F,
  AS_DEFINE_NAME(BUGCHECK_TECH_INFO) = 0x40000083,
  AS_DEFINE_NAME(WINDOWS_NT_CSD_STRING) = 0x40000087,
  AS_DEFINE_NAME(WINDOWS_NT_INFO_STRING) = 0x40000088,
  AS_DEFINE_NAME(WINDOWS_NT_MP_STRING) = 0x40000089,
  AS_DEFINE_NAME(THREAD_TERMINATE_HELD_MUTEX) = 0x4000008A,
  AS_DEFINE_NAME(BUGCODE_PSS_CRASH_INIT) = 0x4000008B,
  AS_DEFINE_NAME(BUGCODE_PSS_CRASH_PROGRESS) = 0x4000008C,
  AS_DEFINE_NAME(BUGCODE_PSS_CRASH_DONE) = 0x4000008D,
  AS_DEFINE_NAME(WINDOWS_NT_INFO_STRING_PLURAL) = 0x4000009D,
  AS_DEFINE_NAME(WINDOWS_NT_RC_STRING) = 0x4000009E,
  AS_DEFINE_NAME(VIDEO_DRIVER_DEBUG_REPORT_REQUEST) = 0x400000AD,
  AS_DEFINE_NAME(HARDWARE_PROFILE_UNDOCKED_STRING) = 0x40010001,
  AS_DEFINE_NAME(HARDWARE_PROFILE_DOCKED_STRING) = 0x40010002,
  AS_DEFINE_NAME(HARDWARE_PROFILE_UNKNOWN_STRING) = 0x40010003,
  AS_DEFINE_NAME(WINLOGON_FATAL_ERROR) = 0xC000021A,
  AS_DEFINE_NAME(MANUALLY_INITIATED_CRASH1) = 0xDEADDEAD,
};


AS_NAMESPACE_END()

#endif  // #ifndef __AS_BUG_CHECK__
