#ifndef __AS_ERRNO_CODE__
#define __AS_ERRNO_CODE__

#include "AllStat.h"

AS_NAMESPACE_BEGIN()

#if AS_UNDEF_VALUES
#ifdef EPERM
#undef EPERM
#endif
#ifdef ENOENT
#undef ENOENT
#endif
#ifdef ESRCH
#undef ESRCH
#endif
#ifdef EINTR
#undef EINTR
#endif
#ifdef EIO
#undef EIO
#endif
#ifdef ENXIO
#undef ENXIO
#endif
#ifdef E2BIG
#undef E2BIG
#endif
#ifdef ENOEXEC
#undef ENOEXEC
#endif
#ifdef EBADF
#undef EBADF
#endif
#ifdef ECHILD
#undef ECHILD
#endif
#ifdef ENOMEM
#undef ENOMEM
#endif
#ifdef EACCES
#undef EACCES
#endif
#ifdef EFAULT
#undef EFAULT
#endif
#ifdef EBUSY
#undef EBUSY
#endif
#ifdef EEXIST
#undef EEXIST
#endif
#ifdef EXDEV
#undef EXDEV
#endif
#ifdef ENODEV
#undef ENODEV
#endif
#ifdef ENOTDIR
#undef ENOTDIR
#endif
#ifdef EISDIR
#undef EISDIR
#endif
#ifdef EINVAL
#undef EINVAL
#endif
#ifdef ENFILE
#undef ENFILE
#endif
#ifdef EMFILE
#undef EMFILE
#endif
#ifdef ENOTTY
#undef ENOTTY
#endif
#ifdef EFBIG
#undef EFBIG
#endif
#ifdef ENOSPC
#undef ENOSPC
#endif
#ifdef ESPIPE
#undef ESPIPE
#endif
#ifdef EROFS
#undef EROFS
#endif
#ifdef EMLINK
#undef EMLINK
#endif
#ifdef EPIPE
#undef EPIPE
#endif
#ifdef EDOM
#undef EDOM
#endif
#ifdef ERANGE
#undef ERANGE
#endif
#endif  // #if AS_UNDEF_VALUES

enum AS_DEFINE_NAME(ERRNO_CODE)
{
  AS_DEFINE_NAME(EPERM) = 1,
  AS_DEFINE_NAME(ENOENT) = 2,
  AS_DEFINE_NAME(ESRCH) = 3,
  AS_DEFINE_NAME(EINTR) = 4,
  AS_DEFINE_NAME(EIO) = 5,
  AS_DEFINE_NAME(ENXIO) = 6,
  AS_DEFINE_NAME(E2BIG) = 7,
  AS_DEFINE_NAME(ENOEXEC) = 8,
  AS_DEFINE_NAME(EBADF) = 9,
  AS_DEFINE_NAME(ECHILD) = 10,
  AS_DEFINE_NAME(EAGAIN_LINUX) = 11,
  AS_DEFINE_NAME(EDEADLK_MAC) = 11,
  AS_DEFINE_NAME(EAGAIN_SOLARIS) = 11,
  AS_DEFINE_NAME(EAGAIN_WINDOWS) = 11,
  AS_DEFINE_NAME(ENOMEM) = 12,
  AS_DEFINE_NAME(EACCES) = 13,
  AS_DEFINE_NAME(EFAULT) = 14,
  AS_DEFINE_NAME(ENOTBLK_LINUX) = 15,
  AS_DEFINE_NAME(ENOTBLK_MAC) = 15,
  AS_DEFINE_NAME(ENOTBLK_SOLARIS) = 15,
  AS_DEFINE_NAME(EBUSY) = 16,
  AS_DEFINE_NAME(EEXIST) = 17,
  AS_DEFINE_NAME(EXDEV) = 18,
  AS_DEFINE_NAME(ENODEV) = 19,
  AS_DEFINE_NAME(ENOTDIR) = 20,
  AS_DEFINE_NAME(EISDIR) = 21,
  AS_DEFINE_NAME(EINVAL) = 22,
  AS_DEFINE_NAME(ENFILE) = 23,
  AS_DEFINE_NAME(EMFILE) = 24,
  AS_DEFINE_NAME(ENOTTY) = 25,
  AS_DEFINE_NAME(ETXTBSY_LINUX) = 26,
  AS_DEFINE_NAME(ETXTBSY_MAC) = 26,
  AS_DEFINE_NAME(ETXTBSY_SOLARIS) = 26,
  AS_DEFINE_NAME(EFBIG) = 27,
  AS_DEFINE_NAME(ENOSPC) = 28,
  AS_DEFINE_NAME(ESPIPE) = 29,
  AS_DEFINE_NAME(EROFS) = 30,
  AS_DEFINE_NAME(EMLINK) = 31,
  AS_DEFINE_NAME(EPIPE) = 32,
  AS_DEFINE_NAME(EDOM) = 33,
  AS_DEFINE_NAME(ERANGE) = 34,
  AS_DEFINE_NAME(EDEADLK_LINUX) = 35,
  AS_DEFINE_NAME(EAGAIN_MAC) = 35,
  AS_DEFINE_NAME(ENOMSG_SOLARIS) = 35,
  AS_DEFINE_NAME(ENAMETOOLONG_LINUX) = 36,
  AS_DEFINE_NAME(EINPROGRESS_MAC) = 36,
  AS_DEFINE_NAME(EIDRM_SOLARIS) = 36,
  AS_DEFINE_NAME(EDEADLK_WINDOWS) = 36,
  AS_DEFINE_NAME(ENOLCK_LINUX) = 37,
  AS_DEFINE_NAME(EALREADY_MAC) = 37,
  AS_DEFINE_NAME(ECHRNG_SOLARIS) = 37,
  AS_DEFINE_NAME(ENOSYS_LINUX) = 38,
  AS_DEFINE_NAME(ENOTSOCK_MAC) = 38,
  AS_DEFINE_NAME(EL2NSYNC_SOLARIS) = 38,
  AS_DEFINE_NAME(ENAMETOOLONG_WINDOWS) = 38,
  AS_DEFINE_NAME(ENOTEMPTY_LINUX) = 39,
  AS_DEFINE_NAME(EDESTADDRREQ_MAC) = 39,
  AS_DEFINE_NAME(EL3HLT_SOLARIS) = 39,
  AS_DEFINE_NAME(ENOLCK_WINDOWS) = 39,
  AS_DEFINE_NAME(ELOOP_LINUX) = 40,
  AS_DEFINE_NAME(EMSGSIZE_MAC) = 40,
  AS_DEFINE_NAME(EL3RST_SOLARIS) = 40,
  AS_DEFINE_NAME(ENOSYS_WINDOWS) = 40,
  AS_DEFINE_NAME(EWOULDBLOCK_LINUX) = 41,
  AS_DEFINE_NAME(EPROTOTYPE_MAC) = 41,
  AS_DEFINE_NAME(ELNRNG_SOLARIS) = 41,
  AS_DEFINE_NAME(ENOTEMPTY_WINDOWS) = 41,
  AS_DEFINE_NAME(ENOMSG_LINUX) = 42,
  AS_DEFINE_NAME(ENOPROTOOPT_MAC) = 42,
  AS_DEFINE_NAME(EUNATCH_SOLARIS) = 42,
  AS_DEFINE_NAME(EILSEQ_WINDOWS) = 42,
  AS_DEFINE_NAME(EIDRM_LINUX) = 43,
  AS_DEFINE_NAME(EPROTONOSUPPORT_MAC) = 43,
  AS_DEFINE_NAME(ENOCSI_SOLARIS) = 43,
  AS_DEFINE_NAME(ECHRNG_LINUX) = 44,
  AS_DEFINE_NAME(ESOCKTNOSUPPORT_MAC) = 44,
  AS_DEFINE_NAME(EL2HLT_SOLARIS) = 44,
  AS_DEFINE_NAME(EL2NSYNC_LINUX) = 45,
  AS_DEFINE_NAME(ENOTSUP_MAC) = 45,
  AS_DEFINE_NAME(EDEADLK_SOLARIS) = 45,
  AS_DEFINE_NAME(EL3HLT_LINUX) = 46,
  AS_DEFINE_NAME(EPFNOSUPPORT_MAC) = 46,
  AS_DEFINE_NAME(ENOLCK_SOLARIS) = 46,
  AS_DEFINE_NAME(EL3RST_LINUX) = 47,
  AS_DEFINE_NAME(EAFNOSUPPORT_MAC) = 47,
  AS_DEFINE_NAME(ECANCELED_SOLARIS) = 47,
  AS_DEFINE_NAME(ELNRNG_LINUX) = 48,
  AS_DEFINE_NAME(EADDRINUSE_MAC) = 48,
  AS_DEFINE_NAME(ENOTSUP_SOLARIS) = 48,
  AS_DEFINE_NAME(EUNATCH_LINUX) = 49,
  AS_DEFINE_NAME(EADDRNOTAVAIL_MAC) = 49,
  AS_DEFINE_NAME(EDQUOT_SOLARIS) = 49,
  AS_DEFINE_NAME(ENOCSI_LINUX) = 50,
  AS_DEFINE_NAME(ENETDOWN_MAC) = 50,
  AS_DEFINE_NAME(EBADE_SOLARIS) = 50,
  AS_DEFINE_NAME(EL2HLT_LINUX) = 51,
  AS_DEFINE_NAME(ENETUNREACH_MAC) = 51,
  AS_DEFINE_NAME(EBADR_SOLARIS) = 51,
  AS_DEFINE_NAME(EBADE_LINUX) = 52,
  AS_DEFINE_NAME(ENETRESET_MAC) = 52,
  AS_DEFINE_NAME(EXFULL_SOLARIS) = 52,
  AS_DEFINE_NAME(EBADR_LINUX) = 53,
  AS_DEFINE_NAME(ECONNABORTED_MAC) = 53,
  AS_DEFINE_NAME(ENOANO_SOLARIS) = 53,
  AS_DEFINE_NAME(EXFULL_LINUX) = 54,
  AS_DEFINE_NAME(ECONNRESET_MAC) = 54,
  AS_DEFINE_NAME(EBADRQC_SOLARIS) = 54,
  AS_DEFINE_NAME(ENOANO_LINUX) = 55,
  AS_DEFINE_NAME(ENOBUFS_MAC) = 55,
  AS_DEFINE_NAME(EBADSLT_SOLARIS) = 55,
  AS_DEFINE_NAME(EBADRQC_LINUX) = 56,
  AS_DEFINE_NAME(EISCONN_MAC) = 56,
  AS_DEFINE_NAME(EDEADLOCK_SOLARIS) = 56,
  AS_DEFINE_NAME(EBADSLT_LINUX) = 57,
  AS_DEFINE_NAME(ENOTCONN_MAC) = 57,
  AS_DEFINE_NAME(EBFONT_SOLARIS) = 57,
  AS_DEFINE_NAME(EDEADLOCK_LINUX) = 58,
  AS_DEFINE_NAME(ESHUTDOWN_MAC) = 58,
  AS_DEFINE_NAME(EOWNERDEAD_SOLARIS) = 58,
  AS_DEFINE_NAME(EBFONT_LINUX) = 59,
  AS_DEFINE_NAME(ETOOMANYREFS_MAC) = 59,
  AS_DEFINE_NAME(ENOTRECOVERABLE_SOLARIS) = 59,
  AS_DEFINE_NAME(ENOSTR_LINUX) = 60,
  AS_DEFINE_NAME(ETIMEDOUT_MAC) = 60,
  AS_DEFINE_NAME(ENOSTR_SOLARIS) = 60,
  AS_DEFINE_NAME(ENODATA_LINUX) = 61,
  AS_DEFINE_NAME(ECONNREFUSED_MAC) = 61,
  AS_DEFINE_NAME(ENODATA_SOLARIS) = 61,
  AS_DEFINE_NAME(ETIME_LINUX) = 62,
  AS_DEFINE_NAME(ELOOP_MAC) = 62,
  AS_DEFINE_NAME(ETIME_SOLARIS) = 62,
  AS_DEFINE_NAME(ENOSR_LINUX) = 63,
  AS_DEFINE_NAME(ENAMETOOLONG_MAC) = 63,
  AS_DEFINE_NAME(ENOSR_SOLARIS) = 63,
  AS_DEFINE_NAME(ENONET_LINUX) = 64,
  AS_DEFINE_NAME(EHOSTDOWN_MAC) = 64,
  AS_DEFINE_NAME(ENONET_SOLARIS) = 64,
  AS_DEFINE_NAME(ENOPKG_LINUX) = 65,
  AS_DEFINE_NAME(EHOSTUNREACH_MAC) = 65,
  AS_DEFINE_NAME(ENOPKG_SOLARIS) = 65,
  AS_DEFINE_NAME(EREMOTE_LINUX) = 66,
  AS_DEFINE_NAME(ENOTEMPTY_MAC) = 66,
  AS_DEFINE_NAME(EREMOTE_SOLARIS) = 66,
  AS_DEFINE_NAME(ENOLINK_LINUX) = 67,
  AS_DEFINE_NAME(EPROCLIM_MAC) = 67,
  AS_DEFINE_NAME(ENOLINK_SOLARIS) = 67,
  AS_DEFINE_NAME(EADV_LINUX) = 68,
  AS_DEFINE_NAME(EUSERS_MAC) = 68,
  AS_DEFINE_NAME(EADV_SOLARIS) = 68,
  AS_DEFINE_NAME(ESRMNT_LINUX) = 69,
  AS_DEFINE_NAME(EDQUOT_MAC) = 69,
  AS_DEFINE_NAME(ESRMNT_SOLARIS) = 69,
  AS_DEFINE_NAME(ECOMM_LINUX) = 70,
  AS_DEFINE_NAME(ESTALE_MAC) = 70,
  AS_DEFINE_NAME(ECOMM_SOLARIS) = 70,
  AS_DEFINE_NAME(EPROTO_LINUX) = 71,
  AS_DEFINE_NAME(EREMOTE_MAC) = 71,
  AS_DEFINE_NAME(EPROTO_SOLARIS) = 71,
  AS_DEFINE_NAME(EMULTIHOP_LINUX) = 72,
  AS_DEFINE_NAME(EBADRPC_MAC) = 72,
  AS_DEFINE_NAME(ELOCKUNMAPPED_SOLARIS) = 72,
  AS_DEFINE_NAME(EDOTDOT_LINUX) = 73,
  AS_DEFINE_NAME(ERPCMISMATCH_MAC) = 73,
  AS_DEFINE_NAME(ENOTACTIVE_SOLARIS) = 73,
  AS_DEFINE_NAME(EBADMSG_LINUX) = 74,
  AS_DEFINE_NAME(EPROGUNAVAIL_MAC) = 74,
  AS_DEFINE_NAME(EMULTIHOP_SOLARIS) = 74,
  AS_DEFINE_NAME(EOVERFLOW_LINUX) = 75,
  AS_DEFINE_NAME(EPROGMISMATCH_MAC) = 75,
  AS_DEFINE_NAME(ENOTUNIQ_LINUX) = 76,
  AS_DEFINE_NAME(EPROCUNAVAIL_MAC) = 76,
  AS_DEFINE_NAME(EBADFD_LINUX) = 77,
  AS_DEFINE_NAME(ENOLCK_MAC) = 77,
  AS_DEFINE_NAME(EBADMSG_SOLARIS) = 77,
  AS_DEFINE_NAME(EREMCHG_LINUX) = 78,
  AS_DEFINE_NAME(ENOSYS_MAC) = 78,
  AS_DEFINE_NAME(ENAMETOOLONG_SOLARIS) = 78,
  AS_DEFINE_NAME(ELIBACC_LINUX) = 79,
  AS_DEFINE_NAME(EFTYPE_MAC) = 79,
  AS_DEFINE_NAME(EOVERFLOW_SOLARIS) = 79,
  AS_DEFINE_NAME(ELIBBAD_LINUX) = 80,
  AS_DEFINE_NAME(EAUTH_MAC) = 80,
  AS_DEFINE_NAME(ENOTUNIQ_SOLARIS) = 80,
  AS_DEFINE_NAME(ELIBSCN_LINUX) = 81,
  AS_DEFINE_NAME(ENEEDAUTH_MAC) = 81,
  AS_DEFINE_NAME(EBADFD_SOLARIS) = 81,
  AS_DEFINE_NAME(ELIBMAX_LINUX) = 82,
  AS_DEFINE_NAME(EPWROFF_MAC) = 82,
  AS_DEFINE_NAME(EREMCHG_SOLARIS) = 82,
  AS_DEFINE_NAME(ELIBEXEC_LINUX) = 83,
  AS_DEFINE_NAME(EDEVERR_MAC) = 83,
  AS_DEFINE_NAME(ELIBACC_SOLARIS) = 83,
  AS_DEFINE_NAME(EILSEQ_LINUX) = 84,
  AS_DEFINE_NAME(EOVERFLOW_MAC) = 84,
  AS_DEFINE_NAME(ELIBBAD_SOLARIS) = 84,
  AS_DEFINE_NAME(ERESTART_LINUX) = 85,
  AS_DEFINE_NAME(EBADEXEC_MAC) = 85,
  AS_DEFINE_NAME(ELIBSCN_SOLARIS) = 85,
  AS_DEFINE_NAME(ESTRPIPE_LINUX) = 86,
  AS_DEFINE_NAME(EBADARCH_MAC) = 86,
  AS_DEFINE_NAME(ELIBMAX_SOLARIS) = 86,
  AS_DEFINE_NAME(EUSERS_LINUX) = 87,
  AS_DEFINE_NAME(ESHLIBVERS_MAC) = 87,
  AS_DEFINE_NAME(ELIBEXEC_SOLARIS) = 87,
  AS_DEFINE_NAME(ENOTSOCK_LINUX) = 88,
  AS_DEFINE_NAME(EBADMACHO_MAC) = 88,
  AS_DEFINE_NAME(EILSEQ_SOLARIS) = 88,
  AS_DEFINE_NAME(EDESTADDRREQ_LINUX) = 89,
  AS_DEFINE_NAME(ECANCELED_MAC) = 89,
  AS_DEFINE_NAME(ENOSYS_SOLARIS) = 89,
  AS_DEFINE_NAME(EMSGSIZE_LINUX) = 90,
  AS_DEFINE_NAME(EIDRM_MAC) = 90,
  AS_DEFINE_NAME(ELOOP_SOLARIS) = 90,
  AS_DEFINE_NAME(EPROTOTYPE_LINUX) = 91,
  AS_DEFINE_NAME(ENOMSG_MAC) = 91,
  AS_DEFINE_NAME(ERESTART_SOLARIS) = 91,
  AS_DEFINE_NAME(ENOPROTOOPT_LINUX) = 92,
  AS_DEFINE_NAME(EILSEQ_MAC) = 92,
  AS_DEFINE_NAME(ESTRPIPE_SOLARIS) = 92,
  AS_DEFINE_NAME(EPROTONOSUPPORT_LINUX) = 93,
  AS_DEFINE_NAME(ENOATTR_MAC) = 93,
  AS_DEFINE_NAME(ENOTEMPTY_SOLARIS) = 93,
  AS_DEFINE_NAME(ESOCKTNOSUPPORT_LINUX) = 94,
  AS_DEFINE_NAME(EBADMSG_MAC) = 94,
  AS_DEFINE_NAME(EUSERS_SOLARIS) = 94,
  AS_DEFINE_NAME(EOPNOTSUPP_LINUX) = 95,
  AS_DEFINE_NAME(EMULTIHOP_MAC) = 95,
  AS_DEFINE_NAME(ENOTSOCK_SOLARIS) = 95,
  AS_DEFINE_NAME(EPFNOSUPPORT_LINUX) = 96,
  AS_DEFINE_NAME(ENODATA_MAC) = 96,
  AS_DEFINE_NAME(EDESTADDRREQ_SOLARIS) = 96,
  AS_DEFINE_NAME(EAFNOSUPPORT_LINUX) = 97,
  AS_DEFINE_NAME(ENOLINK_MAC) = 97,
  AS_DEFINE_NAME(EMSGSIZE_SOLARIS) = 97,
  AS_DEFINE_NAME(EADDRINUSE_LINUX) = 98,
  AS_DEFINE_NAME(ENOSR_MAC) = 98,
  AS_DEFINE_NAME(EPROTOTYPE_SOLARIS) = 98,
  AS_DEFINE_NAME(EADDRNOTAVAIL_LINUX) = 99,
  AS_DEFINE_NAME(ENOSTR_MAC) = 99,
  AS_DEFINE_NAME(ENOPROTOOPT_SOLARIS) = 99,
  AS_DEFINE_NAME(ENETDOWN_LINUX) = 100,
  AS_DEFINE_NAME(EPROTO_MAC) = 100,
  AS_DEFINE_NAME(EADDRINUSE_WINDOWS) = 100,
  AS_DEFINE_NAME(ENETUNREACH_LINUX) = 101,
  AS_DEFINE_NAME(ETIME_MAC) = 101,
  AS_DEFINE_NAME(EADDRNOTAVAIL_WINDOWS) = 101,
  AS_DEFINE_NAME(ENETRESET_LINUX) = 102,
  AS_DEFINE_NAME(EOPNOTSUPP_MAC) = 102,
  AS_DEFINE_NAME(EAFNOSUPPORT_WINDOWS) = 102,
  AS_DEFINE_NAME(ECONNABORTED_LINUX) = 103,
  AS_DEFINE_NAME(ENOPOLICY_MAC) = 103,
  AS_DEFINE_NAME(EALREADY_WINDOWS) = 103,
  AS_DEFINE_NAME(ECONNRESET_LINUX) = 104,
  AS_DEFINE_NAME(ENOTRECOVERABLE_MAC) = 104,
  AS_DEFINE_NAME(EBADMSG_WINDOWS) = 104,
  AS_DEFINE_NAME(ENOBUFS_LINUX) = 105,
  AS_DEFINE_NAME(EOWNERDEAD_MAC) = 105,
  AS_DEFINE_NAME(ECANCELED_WINDOWS) = 105,
  AS_DEFINE_NAME(EISCONN_LINUX) = 106,
  AS_DEFINE_NAME(EQFULL_MAC) = 106,
  AS_DEFINE_NAME(ELAST_MAC) = 106,
  AS_DEFINE_NAME(ECONNABORTED_WINDOWS) = 106,
  AS_DEFINE_NAME(ENOTCONN_LINUX) = 107,
  AS_DEFINE_NAME(ECONNREFUSED_WINDOWS) = 107,
  AS_DEFINE_NAME(ESHUTDOWN_LINUX) = 108,
  AS_DEFINE_NAME(ECONNRESET_WINDOWS) = 108,
  AS_DEFINE_NAME(ETOOMANYREFS_LINUX) = 109,
  AS_DEFINE_NAME(EDESTADDRREQ_WINDOWS) = 109,
  AS_DEFINE_NAME(ETIMEDOUT_LINUX) = 110,
  AS_DEFINE_NAME(EHOSTUNREACH_WINDOWS) = 110,
  AS_DEFINE_NAME(ECONNREFUSED_LINUX) = 111,
  AS_DEFINE_NAME(EIDRM_WINDOWS) = 111,
  AS_DEFINE_NAME(EHOSTDOWN_LINUX) = 112,
  AS_DEFINE_NAME(EINPROGRESS_WINDOWS) = 112,
  AS_DEFINE_NAME(EHOSTUNREACH_LINUX) = 113,
  AS_DEFINE_NAME(EISCONN_WINDOWS) = 113,
  AS_DEFINE_NAME(EALREADY_LINUX) = 114,
  AS_DEFINE_NAME(ELOOP_WINDOWS) = 114,
  AS_DEFINE_NAME(EINPROGRESS_LINUX) = 115,
  AS_DEFINE_NAME(EMSGSIZE_WINDOWS) = 115,
  AS_DEFINE_NAME(ESTALE_LINUX) = 116,
  AS_DEFINE_NAME(ENETDOWN_WINDOWS) = 116,
  AS_DEFINE_NAME(EUCLEAN_LINUX) = 117,
  AS_DEFINE_NAME(ENETRESET_WINDOWS) = 117,
  AS_DEFINE_NAME(ENOTNAM_LINUX) = 118,
  AS_DEFINE_NAME(ENETUNREACH_WINDOWS) = 118,
  AS_DEFINE_NAME(ENAVAIL_LINUX) = 119,
  AS_DEFINE_NAME(ENOBUFS_WINDOWS) = 119,
  AS_DEFINE_NAME(EISNAM_LINUX) = 120,
  AS_DEFINE_NAME(EPROTONOSUPPORT_SOLARIS) = 120,
  AS_DEFINE_NAME(ENODATA_WINDOWS) = 120,
  AS_DEFINE_NAME(EREMOTEIO_LINUX) = 121,
  AS_DEFINE_NAME(ESOCKTNOSUPPORT_SOLARIS) = 121,
  AS_DEFINE_NAME(ENOLINK_WINDOWS) = 121,
  AS_DEFINE_NAME(EOPNOTSUPP_SOLARIS) = 122,
  AS_DEFINE_NAME(ENOMSG_WINDOWS) = 122,
  AS_DEFINE_NAME(EPFNOSUPPORT_SOLARIS) = 123,
  AS_DEFINE_NAME(ENOPROTOOPT_WINDOWS) = 123,
  AS_DEFINE_NAME(EAFNOSUPPORT_SOLARIS) = 124,
  AS_DEFINE_NAME(ENOSR_WINDOWS) = 124,
  AS_DEFINE_NAME(EADDRINUSE_SOLARIS) = 125,
  AS_DEFINE_NAME(ENOSTR_WINDOWS) = 125,
  AS_DEFINE_NAME(EADDRNOTAVAIL_SOLARIS) = 126,
  AS_DEFINE_NAME(ENOTCONN_WINDOWS) = 126,
  AS_DEFINE_NAME(ENETDOWN_SOLARIS) = 127,
  AS_DEFINE_NAME(ENOTRECOVERABLE_WINDOWS) = 127,
  AS_DEFINE_NAME(ENETUNREACH_SOLARIS) = 128,
  AS_DEFINE_NAME(ENOTSOCK_WINDOWS) = 128,
  AS_DEFINE_NAME(ENETRESET_SOLARIS) = 129,
  AS_DEFINE_NAME(ENOTSUP_WINDOWS) = 129,
  AS_DEFINE_NAME(ECONNABORTED_SOLARIS) = 130,
  AS_DEFINE_NAME(EOPNOTSUPP_WINDOWS) = 130,
  AS_DEFINE_NAME(ECONNRESET_SOLARIS) = 131,
  AS_DEFINE_NAME(EOTHER_WINDOWS) = 131,
  AS_DEFINE_NAME(ENOBUFS_SOLARIS) = 132,
  AS_DEFINE_NAME(EOVERFLOW_WINDOWS) = 132,
  AS_DEFINE_NAME(EISCONN_SOLARIS) = 133,
  AS_DEFINE_NAME(EOWNERDEAD_WINDOWS) = 133,
  AS_DEFINE_NAME(ENOTCONN_SOLARIS) = 134,
  AS_DEFINE_NAME(EPROTO_WINDOWS) = 134,
  AS_DEFINE_NAME(EPROTONOSUPPORT_WINDOWS) = 135,
  AS_DEFINE_NAME(EPROTOTYPE_WINDOWS) = 136,
  AS_DEFINE_NAME(ETIME_WINDOWS) = 137,
  AS_DEFINE_NAME(ETIMEDOUT_WINDOWS) = 138,
  AS_DEFINE_NAME(ETXTBSY_WINDOWS) = 139,
  AS_DEFINE_NAME(EWOULDBLOCK_WINDOWS) = 140,
  AS_DEFINE_NAME(ESHUTDOWN_SOLARIS) = 143,
  AS_DEFINE_NAME(ETOOMANYREFS_SOLARIS) = 144,
  AS_DEFINE_NAME(ETIMEDOUT_SOLARIS) = 145,
  AS_DEFINE_NAME(ECONNREFUSED_SOLARIS) = 146,
  AS_DEFINE_NAME(EHOSTDOWN_SOLARIS) = 147,
  AS_DEFINE_NAME(EHOSTUNREACH_SOLARIS) = 148,
  AS_DEFINE_NAME(EALREADY_SOLARIS) = 149,
  AS_DEFINE_NAME(EINPROGRESS_SOLARIS) = 150,
  AS_DEFINE_NAME(ESTALE_SOLARIS) = 151,
  AS_DEFINE_NAME(ECVCERORR_MAC) = 256,
  AS_DEFINE_NAME(ERESTARTSYS_LINUX) = 512,
  AS_DEFINE_NAME(ECVPERORR_MAC) = 512,
  AS_DEFINE_NAME(ERESTARTNOINTR_LINUX) = 513,
};


AS_NAMESPACE_END()

#endif  // #ifndef __AS_ERRNO_CODE__
