#ifndef __AS_HTTP_STATUS_CODE__
#define __AS_HTTP_STATUS_CODE__

#include "AllStat.h"

AS_NAMESPACE_BEGIN()

#if AS_UNDEF_VALUES
#ifdef HTTP_STATUS_CONTINUE
#undef HTTP_STATUS_CONTINUE
#endif
#ifdef HTTP_STATUS_SWITCH_PROTOCOLS
#undef HTTP_STATUS_SWITCH_PROTOCOLS
#endif
#ifdef HTTP_STATUS_PROCESSING
#undef HTTP_STATUS_PROCESSING
#endif
#ifdef HTTP_EARLY_HINTS
#undef HTTP_EARLY_HINTS
#endif
#ifdef HTTP_STATUS_OK
#undef HTTP_STATUS_OK
#endif
#ifdef HTTP_STATUS_CREATED
#undef HTTP_STATUS_CREATED
#endif
#ifdef HTTP_STATUS_ACCEPTED
#undef HTTP_STATUS_ACCEPTED
#endif
#ifdef HTTP_STATUS_NON_AUTH_INFORMATION
#undef HTTP_STATUS_NON_AUTH_INFORMATION
#endif
#ifdef HTTP_STATUS_NO_CONTENT
#undef HTTP_STATUS_NO_CONTENT
#endif
#ifdef HTTP_STATUS_RESET_CONTENT
#undef HTTP_STATUS_RESET_CONTENT
#endif
#ifdef HTTP_STATUS_PARTIAL_CONTENT
#undef HTTP_STATUS_PARTIAL_CONTENT
#endif
#ifdef HTTP_STATUS_MULTI
#undef HTTP_STATUS_MULTI
#endif
#ifdef HTTP_STATUS_ALREADY_REPORTED
#undef HTTP_STATUS_ALREADY_REPORTED
#endif
#ifdef HTTP_STATUS_FINE
#undef HTTP_STATUS_FINE
#endif
#ifdef HTTP_STATUS_IM_USED
#undef HTTP_STATUS_IM_USED
#endif
#ifdef HTTP_STATUS_AMBIGUOUS
#undef HTTP_STATUS_AMBIGUOUS
#endif
#ifdef HTTP_STATUS_MOVED
#undef HTTP_STATUS_MOVED
#endif
#ifdef HTTP_STATUS_REDIRECT
#undef HTTP_STATUS_REDIRECT
#endif
#ifdef HTTP_STATUS_REDIRECT_METHOD
#undef HTTP_STATUS_REDIRECT_METHOD
#endif
#ifdef HTTP_STATUS_NOT_MODIFIED
#undef HTTP_STATUS_NOT_MODIFIED
#endif
#ifdef HTTP_STATUS_USE_PROXY
#undef HTTP_STATUS_USE_PROXY
#endif
#ifdef HTTP_STATUS_SWITCH_PROXY
#undef HTTP_STATUS_SWITCH_PROXY
#endif
#ifdef HTTP_STATUS_TEMPORARY_REDIRECT
#undef HTTP_STATUS_TEMPORARY_REDIRECT
#endif
#ifdef HTTP_STATUS_PERMANENT_REDIRECT
#undef HTTP_STATUS_PERMANENT_REDIRECT
#endif
#ifdef HTTP_STATUS_BAD_REQUEST
#undef HTTP_STATUS_BAD_REQUEST
#endif
#ifdef HTTP_STATUS_DENIED
#undef HTTP_STATUS_DENIED
#endif
#ifdef HTTP_STATUS_PAYMENT_REQ
#undef HTTP_STATUS_PAYMENT_REQ
#endif
#ifdef HTTP_STATUS_FORBIDDEN
#undef HTTP_STATUS_FORBIDDEN
#endif
#ifdef HTTP_STATUS_NOT_FOUND
#undef HTTP_STATUS_NOT_FOUND
#endif
#ifdef HTTP_STATUS_BAD_METHOD
#undef HTTP_STATUS_BAD_METHOD
#endif
#ifdef HTTP_STATUS_NONE_ACCEPTABLE
#undef HTTP_STATUS_NONE_ACCEPTABLE
#endif
#ifdef HTTP_STATUS_PROXY_AUTH_REQ
#undef HTTP_STATUS_PROXY_AUTH_REQ
#endif
#ifdef HTTP_STATUS_REQUEST_TIMEOUT
#undef HTTP_STATUS_REQUEST_TIMEOUT
#endif
#ifdef HTTP_STATUS_CONFLICT
#undef HTTP_STATUS_CONFLICT
#endif
#ifdef HTTP_STATUS_GONE
#undef HTTP_STATUS_GONE
#endif
#ifdef HTTP_STATUS_LENGTH_REQUIRED
#undef HTTP_STATUS_LENGTH_REQUIRED
#endif
#ifdef HTTP_STATUS_PRECOND_FAILED
#undef HTTP_STATUS_PRECOND_FAILED
#endif
#ifdef HTTP_STATUS_REQUEST_TOO_LARGE
#undef HTTP_STATUS_REQUEST_TOO_LARGE
#endif
#ifdef HTTP_STATUS_URI_TOO_LONG
#undef HTTP_STATUS_URI_TOO_LONG
#endif
#ifdef HTTP_STATUS_UNSUPPORTED_MEDIA
#undef HTTP_STATUS_UNSUPPORTED_MEDIA
#endif
#ifdef HTTP_STATUS_RANGE_NOT_SATISFIABLE
#undef HTTP_STATUS_RANGE_NOT_SATISFIABLE
#endif
#ifdef HTTP_STATUS_EXPECTATION_FAILED
#undef HTTP_STATUS_EXPECTATION_FAILED
#endif
#ifdef HTTP_STATUS_TEAPOT
#undef HTTP_STATUS_TEAPOT
#endif
#ifdef HTTP_STATUS_PAGE_EXPIRED
#undef HTTP_STATUS_PAGE_EXPIRED
#endif
#ifdef HTTP_STATUS_METHOD_FAILURE
#undef HTTP_STATUS_METHOD_FAILURE
#endif
#ifdef HTTP_STATUS_ENHENCE_CALM
#undef HTTP_STATUS_ENHENCE_CALM
#endif
#ifdef HTTP_STATUS_MISDIRECTED_REQUEST
#undef HTTP_STATUS_MISDIRECTED_REQUEST
#endif
#ifdef HTTP_STATUS_UNPROCESSABLE_ENTITY
#undef HTTP_STATUS_UNPROCESSABLE_ENTITY
#endif
#ifdef HTTP_STATUS_LOCKED
#undef HTTP_STATUS_LOCKED
#endif
#ifdef HTTP_STATUS_FAILED_DEPENDENCY
#undef HTTP_STATUS_FAILED_DEPENDENCY
#endif
#ifdef HTTP_STATUS_TOO_EARLY
#undef HTTP_STATUS_TOO_EARLY
#endif
#ifdef HTTP_STATUS_UPGRADE_REQUIRED
#undef HTTP_STATUS_UPGRADE_REQUIRED
#endif
#ifdef HTTP_STATUS_PRECONDITION_REQUIRED
#undef HTTP_STATUS_PRECONDITION_REQUIRED
#endif
#ifdef HTTP_STATUS_TOO_MANY_REQUESTS
#undef HTTP_STATUS_TOO_MANY_REQUESTS
#endif
#ifdef HTTP_STATUS_HEADER_FIELDS_TOO_LARGE_2
#undef HTTP_STATUS_HEADER_FIELDS_TOO_LARGE_2
#endif
#ifdef HTTP_STATUS_HEADER_FIELDS_TOO_LARGE
#undef HTTP_STATUS_HEADER_FIELDS_TOO_LARGE
#endif
#ifdef HTTP_STATUS_LOGIN_TIMEOUT
#undef HTTP_STATUS_LOGIN_TIMEOUT
#endif
#ifdef HTTP_STATUS_BO_RESPONSE
#undef HTTP_STATUS_BO_RESPONSE
#endif
#ifdef HTTP_STATUS_RETRY_WITH
#undef HTTP_STATUS_RETRY_WITH
#endif
#ifdef HTTP_STATUS_BLOCKED
#undef HTTP_STATUS_BLOCKED
#endif
#ifdef HTTP_STATUS_IIS_REDIRECT
#undef HTTP_STATUS_IIS_REDIRECT
#endif
#ifdef HTTP_STATUS_REQUEST_HEADER_TOO_LARGE
#undef HTTP_STATUS_REQUEST_HEADER_TOO_LARGE
#endif
#ifdef HTTP_STATUS_CERTIFICATE_ERROR
#undef HTTP_STATUS_CERTIFICATE_ERROR
#endif
#ifdef HTTP_STATUS_CERTIFICATE_REQUIRED
#undef HTTP_STATUS_CERTIFICATE_REQUIRED
#endif
#ifdef HTTP_STATUS_HTTP_TO_HTTPS_PORT
#undef HTTP_STATUS_HTTP_TO_HTTPS_PORT
#endif
#ifdef HTTP_STATUS_INVALID_TOKEN
#undef HTTP_STATUS_INVALID_TOKEN
#endif
#ifdef HTTP_STATUS_TOKEN_REQUIRED
#undef HTTP_STATUS_TOKEN_REQUIRED
#endif
#ifdef HTTP_STATUS_CLIENT_CLOSED_REQUEST
#undef HTTP_STATUS_CLIENT_CLOSED_REQUEST
#endif
#ifdef HTTP_STATUS_SERVER_ERROR
#undef HTTP_STATUS_SERVER_ERROR
#endif
#ifdef HTTP_STATUS_NOT_SUPPORTED
#undef HTTP_STATUS_NOT_SUPPORTED
#endif
#ifdef HTTP_STATUS_BAD_GATEWAY
#undef HTTP_STATUS_BAD_GATEWAY
#endif
#ifdef HTTP_STATUS_SERVICE_UNAVAIL
#undef HTTP_STATUS_SERVICE_UNAVAIL
#endif
#ifdef HTTP_STATUS_GATEWAY_TIMEOUT
#undef HTTP_STATUS_GATEWAY_TIMEOUT
#endif
#ifdef HTTP_STATUS_VERSION_NOT_SUPPORTED
#undef HTTP_STATUS_VERSION_NOT_SUPPORTED
#endif
#ifdef HTTP_STATUS_VARIANT_ALSO_NEGOTIATES
#undef HTTP_STATUS_VARIANT_ALSO_NEGOTIATES
#endif
#ifdef HTTP_STATUS_INSUFFICIENT_STORAGE
#undef HTTP_STATUS_INSUFFICIENT_STORAGE
#endif
#ifdef HTTP_STATUS_LOOP_DETECTED
#undef HTTP_STATUS_LOOP_DETECTED
#endif
#ifdef HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED
#undef HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED
#endif
#ifdef HTTP_STATUS_NOT_EXTENDED
#undef HTTP_STATUS_NOT_EXTENDED
#endif
#ifdef HTTP_STATUS_AUTHENTICATION_REQUIRED
#undef HTTP_STATUS_AUTHENTICATION_REQUIRED
#endif
#ifdef HTTP_STATUS_UNKNOWN_ERROR
#undef HTTP_STATUS_UNKNOWN_ERROR
#endif
#ifdef HTTP_STATUS_SERVER_IS_DOWN
#undef HTTP_STATUS_SERVER_IS_DOWN
#endif
#ifdef HTTP_STATUS_CONNECTION_TIMED_OUT
#undef HTTP_STATUS_CONNECTION_TIMED_OUT
#endif
#ifdef HTTP_STATUS_ORIGIN_IS_UNREACHABLE
#undef HTTP_STATUS_ORIGIN_IS_UNREACHABLE
#endif
#ifdef HTTP_STATUS_TIMEOUT_OCCURED
#undef HTTP_STATUS_TIMEOUT_OCCURED
#endif
#ifdef HTTP_STATUS_HANDSHAKE_FAILED
#undef HTTP_STATUS_HANDSHAKE_FAILED
#endif
#ifdef HTTP_STATUS_INVALID_CERTIFICATE
#undef HTTP_STATUS_INVALID_CERTIFICATE
#endif
#ifdef HTTP_STATUS_RAILGUN_ERROR
#undef HTTP_STATUS_RAILGUN_ERROR
#endif
#ifdef HTTP_STATUS_SITE_OVERLOADED
#undef HTTP_STATUS_SITE_OVERLOADED
#endif
#ifdef HTTP_STATUS_SITE_FROZEN
#undef HTTP_STATUS_SITE_FROZEN
#endif
#ifdef HTTP_STATUS_UNAUTHORIZED
#undef HTTP_STATUS_UNAUTHORIZED
#endif
#ifdef HTTP_STATUS_NETWORK_READ_TIMEOUT
#undef HTTP_STATUS_NETWORK_READ_TIMEOUT
#endif
#endif  // #if AS_UNDEF_VALUES

enum AS_DEFINE_NAME(HTTP_STATUS_CODE)
{
  AS_DEFINE_NAME(HTTP_STATUS_CONTINUE) = 100,
  AS_DEFINE_NAME(HTTP_STATUS_SWITCH_PROTOCOLS) = 101,
  AS_DEFINE_NAME(HTTP_STATUS_PROCESSING) = 102,
  AS_DEFINE_NAME(HTTP_EARLY_HINTS) = 103,
  AS_DEFINE_NAME(HTTP_STATUS_OK) = 200,
  AS_DEFINE_NAME(HTTP_STATUS_CREATED) = 201,
  AS_DEFINE_NAME(HTTP_STATUS_ACCEPTED) = 202,
  AS_DEFINE_NAME(HTTP_STATUS_NON_AUTH_INFORMATION) = 203,
  AS_DEFINE_NAME(HTTP_STATUS_NO_CONTENT) = 204,
  AS_DEFINE_NAME(HTTP_STATUS_RESET_CONTENT) = 205,
  AS_DEFINE_NAME(HTTP_STATUS_PARTIAL_CONTENT) = 206,
  AS_DEFINE_NAME(HTTP_STATUS_MULTI) = 207,
  AS_DEFINE_NAME(HTTP_STATUS_ALREADY_REPORTED) = 208,
  AS_DEFINE_NAME(HTTP_STATUS_FINE) = 218,
  AS_DEFINE_NAME(HTTP_STATUS_IM_USED) = 226,
  AS_DEFINE_NAME(HTTP_STATUS_AMBIGUOUS) = 300,
  AS_DEFINE_NAME(HTTP_STATUS_MOVED) = 301,
  AS_DEFINE_NAME(HTTP_STATUS_REDIRECT) = 302,
  AS_DEFINE_NAME(HTTP_STATUS_REDIRECT_METHOD) = 303,
  AS_DEFINE_NAME(HTTP_STATUS_NOT_MODIFIED) = 304,
  AS_DEFINE_NAME(HTTP_STATUS_USE_PROXY) = 305,
  AS_DEFINE_NAME(HTTP_STATUS_SWITCH_PROXY) = 306,
  AS_DEFINE_NAME(HTTP_STATUS_TEMPORARY_REDIRECT) = 307,
  AS_DEFINE_NAME(HTTP_STATUS_PERMANENT_REDIRECT) = 308,
  AS_DEFINE_NAME(HTTP_STATUS_BAD_REQUEST) = 400,
  AS_DEFINE_NAME(HTTP_STATUS_DENIED) = 401,
  AS_DEFINE_NAME(HTTP_STATUS_PAYMENT_REQ) = 402,
  AS_DEFINE_NAME(HTTP_STATUS_FORBIDDEN) = 403,
  AS_DEFINE_NAME(HTTP_STATUS_NOT_FOUND) = 404,
  AS_DEFINE_NAME(HTTP_STATUS_BAD_METHOD) = 405,
  AS_DEFINE_NAME(HTTP_STATUS_NONE_ACCEPTABLE) = 406,
  AS_DEFINE_NAME(HTTP_STATUS_PROXY_AUTH_REQ) = 407,
  AS_DEFINE_NAME(HTTP_STATUS_REQUEST_TIMEOUT) = 408,
  AS_DEFINE_NAME(HTTP_STATUS_CONFLICT) = 409,
  AS_DEFINE_NAME(HTTP_STATUS_GONE) = 410,
  AS_DEFINE_NAME(HTTP_STATUS_LENGTH_REQUIRED) = 411,
  AS_DEFINE_NAME(HTTP_STATUS_PRECOND_FAILED) = 412,
  AS_DEFINE_NAME(HTTP_STATUS_REQUEST_TOO_LARGE) = 413,
  AS_DEFINE_NAME(HTTP_STATUS_URI_TOO_LONG) = 414,
  AS_DEFINE_NAME(HTTP_STATUS_UNSUPPORTED_MEDIA) = 415,
  AS_DEFINE_NAME(HTTP_STATUS_RANGE_NOT_SATISFIABLE) = 416,
  AS_DEFINE_NAME(HTTP_STATUS_EXPECTATION_FAILED) = 417,
  AS_DEFINE_NAME(HTTP_STATUS_TEAPOT) = 418,
  AS_DEFINE_NAME(HTTP_STATUS_PAGE_EXPIRED) = 419,
  AS_DEFINE_NAME(HTTP_STATUS_METHOD_FAILURE) = 420,
  AS_DEFINE_NAME(HTTP_STATUS_ENHENCE_CALM) = 420,
  AS_DEFINE_NAME(HTTP_STATUS_MISDIRECTED_REQUEST) = 421,
  AS_DEFINE_NAME(HTTP_STATUS_UNPROCESSABLE_ENTITY) = 422,
  AS_DEFINE_NAME(HTTP_STATUS_LOCKED) = 423,
  AS_DEFINE_NAME(HTTP_STATUS_FAILED_DEPENDENCY) = 424,
  AS_DEFINE_NAME(HTTP_STATUS_TOO_EARLY) = 425,
  AS_DEFINE_NAME(HTTP_STATUS_UPGRADE_REQUIRED) = 426,
  AS_DEFINE_NAME(HTTP_STATUS_PRECONDITION_REQUIRED) = 428,
  AS_DEFINE_NAME(HTTP_STATUS_TOO_MANY_REQUESTS) = 429,
  AS_DEFINE_NAME(HTTP_STATUS_HEADER_FIELDS_TOO_LARGE_2) = 430,
  AS_DEFINE_NAME(HTTP_STATUS_HEADER_FIELDS_TOO_LARGE) = 431,
  AS_DEFINE_NAME(HTTP_STATUS_LOGIN_TIMEOUT) = 440,
  AS_DEFINE_NAME(HTTP_STATUS_BO_RESPONSE) = 444,
  AS_DEFINE_NAME(HTTP_STATUS_RETRY_WITH) = 449,
  AS_DEFINE_NAME(HTTP_STATUS_BLOCKED) = 450,
  AS_DEFINE_NAME(HTTP_STATUS_IIS_REDIRECT) = 451,
  AS_DEFINE_NAME(HTTP_STATUS_REQUEST_HEADER_TOO_LARGE) = 494,
  AS_DEFINE_NAME(HTTP_STATUS_CERTIFICATE_ERROR) = 495,
  AS_DEFINE_NAME(HTTP_STATUS_CERTIFICATE_REQUIRED) = 496,
  AS_DEFINE_NAME(HTTP_STATUS_HTTP_TO_HTTPS_PORT) = 497,
  AS_DEFINE_NAME(HTTP_STATUS_INVALID_TOKEN) = 498,
  AS_DEFINE_NAME(HTTP_STATUS_TOKEN_REQUIRED) = 499,
  AS_DEFINE_NAME(HTTP_STATUS_CLIENT_CLOSED_REQUEST) = 499,
  AS_DEFINE_NAME(HTTP_STATUS_SERVER_ERROR) = 500,
  AS_DEFINE_NAME(HTTP_STATUS_NOT_SUPPORTED) = 501,
  AS_DEFINE_NAME(HTTP_STATUS_BAD_GATEWAY) = 502,
  AS_DEFINE_NAME(HTTP_STATUS_SERVICE_UNAVAIL) = 503,
  AS_DEFINE_NAME(HTTP_STATUS_GATEWAY_TIMEOUT) = 504,
  AS_DEFINE_NAME(HTTP_STATUS_VERSION_NOT_SUPPORTED) = 505,
  AS_DEFINE_NAME(HTTP_STATUS_VARIANT_ALSO_NEGOTIATES) = 506,
  AS_DEFINE_NAME(HTTP_STATUS_INSUFFICIENT_STORAGE) = 507,
  AS_DEFINE_NAME(HTTP_STATUS_LOOP_DETECTED) = 508,
  AS_DEFINE_NAME(HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED) = 509,
  AS_DEFINE_NAME(HTTP_STATUS_NOT_EXTENDED) = 510,
  AS_DEFINE_NAME(HTTP_STATUS_AUTHENTICATION_REQUIRED) = 511,
  AS_DEFINE_NAME(HTTP_STATUS_UNKNOWN_ERROR) = 520,
  AS_DEFINE_NAME(HTTP_STATUS_SERVER_IS_DOWN) = 521,
  AS_DEFINE_NAME(HTTP_STATUS_CONNECTION_TIMED_OUT) = 522,
  AS_DEFINE_NAME(HTTP_STATUS_ORIGIN_IS_UNREACHABLE) = 523,
  AS_DEFINE_NAME(HTTP_STATUS_TIMEOUT_OCCURED) = 524,
  AS_DEFINE_NAME(HTTP_STATUS_HANDSHAKE_FAILED) = 525,
  AS_DEFINE_NAME(HTTP_STATUS_INVALID_CERTIFICATE) = 526,
  AS_DEFINE_NAME(HTTP_STATUS_RAILGUN_ERROR) = 527,
  AS_DEFINE_NAME(HTTP_STATUS_SITE_OVERLOADED) = 529,
  AS_DEFINE_NAME(HTTP_STATUS_SITE_FROZEN) = 530,
  AS_DEFINE_NAME(HTTP_STATUS_UNAUTHORIZED) = 561,
  AS_DEFINE_NAME(HTTP_STATUS_NETWORK_READ_TIMEOUT) = 598,
};


AS_NAMESPACE_END()

#endif  // #ifndef __AS_HTTP_STATUS_CODE__
