#ifndef __AS_KERN_RETURN__
#define __AS_KERN_RETURN__

#include "AllStat.h"

AS_NAMESPACE_BEGIN()

#if AS_UNDEF_VALUES
#ifdef KERN_SUCCESS
#undef KERN_SUCCESS
#endif
#ifdef KERN_INVALID_ADDRESS
#undef KERN_INVALID_ADDRESS
#endif
#ifdef KERN_PROTECTION_FAILURE
#undef KERN_PROTECTION_FAILURE
#endif
#ifdef KERN_NO_SPACE
#undef KERN_NO_SPACE
#endif
#ifdef KERN_INVALID_ARGUMENT
#undef KERN_INVALID_ARGUMENT
#endif
#ifdef KERN_FAILURE
#undef KERN_FAILURE
#endif
#ifdef KERN_RESOURCE_SHORTAGE
#undef KERN_RESOURCE_SHORTAGE
#endif
#ifdef KERN_NOT_RECEIVER
#undef KERN_NOT_RECEIVER
#endif
#ifdef KERN_NO_ACCESS
#undef KERN_NO_ACCESS
#endif
#ifdef KERN_MEMORY_FAILURE
#undef KERN_MEMORY_FAILURE
#endif
#ifdef KERN_MEMORY_ERROR
#undef KERN_MEMORY_ERROR
#endif
#ifdef KERN_ALREADY_IN_SET
#undef KERN_ALREADY_IN_SET
#endif
#ifdef KERN_NOT_IN_SET
#undef KERN_NOT_IN_SET
#endif
#ifdef KERN_NAME_EXISTS
#undef KERN_NAME_EXISTS
#endif
#ifdef KERN_ABORTED
#undef KERN_ABORTED
#endif
#ifdef KERN_INVALID_NAME
#undef KERN_INVALID_NAME
#endif
#ifdef KERN_INVALID_TASK
#undef KERN_INVALID_TASK
#endif
#ifdef KERN_INVALID_RIGHT
#undef KERN_INVALID_RIGHT
#endif
#ifdef KERN_INVALID_VALUE
#undef KERN_INVALID_VALUE
#endif
#ifdef KERN_UREFS_OVERFLOW
#undef KERN_UREFS_OVERFLOW
#endif
#ifdef KERN_INVALID_CAPABILITY
#undef KERN_INVALID_CAPABILITY
#endif
#ifdef KERN_RIGHT_EXISTS
#undef KERN_RIGHT_EXISTS
#endif
#ifdef KERN_INVALID_HOST
#undef KERN_INVALID_HOST
#endif
#ifdef KERN_MEMORY_PRESENT
#undef KERN_MEMORY_PRESENT
#endif
#ifdef KERN_MEMORY_DATA_MOVED
#undef KERN_MEMORY_DATA_MOVED
#endif
#ifdef KERN_MEMORY_RESTART_COPY
#undef KERN_MEMORY_RESTART_COPY
#endif
#ifdef KERN_INVALID_PROCESSOR_SET
#undef KERN_INVALID_PROCESSOR_SET
#endif
#ifdef KERN_POLICY_LIMIT
#undef KERN_POLICY_LIMIT
#endif
#ifdef KERN_INVALID_POLICY
#undef KERN_INVALID_POLICY
#endif
#ifdef KERN_INVALID_OBJECT
#undef KERN_INVALID_OBJECT
#endif
#ifdef KERN_ALREADY_WAITING
#undef KERN_ALREADY_WAITING
#endif
#ifdef KERN_DEFAULT_SET
#undef KERN_DEFAULT_SET
#endif
#ifdef KERN_EXCEPTION_PROTECTED
#undef KERN_EXCEPTION_PROTECTED
#endif
#ifdef KERN_INVALID_LEDGER
#undef KERN_INVALID_LEDGER
#endif
#ifdef KERN_INVALID_MEMORY_CONTROL
#undef KERN_INVALID_MEMORY_CONTROL
#endif
#ifdef KERN_INVALID_SECURITY
#undef KERN_INVALID_SECURITY
#endif
#ifdef KERN_NOT_DEPRESSED
#undef KERN_NOT_DEPRESSED
#endif
#ifdef KERN_TERMINATED
#undef KERN_TERMINATED
#endif
#ifdef KERN_LOCK_SET_DESTROYED
#undef KERN_LOCK_SET_DESTROYED
#endif
#ifdef KERN_LOCK_UNSTABLE
#undef KERN_LOCK_UNSTABLE
#endif
#ifdef KERN_LOCK_OWNED
#undef KERN_LOCK_OWNED
#endif
#ifdef KERN_LOCK_OWNED_SELF
#undef KERN_LOCK_OWNED_SELF
#endif
#ifdef KERN_SEMAPHORE_DESTROYED
#undef KERN_SEMAPHORE_DESTROYED
#endif
#ifdef KERN_RPC_SERVER_TERMINATED
#undef KERN_RPC_SERVER_TERMINATED
#endif
#ifdef KERN_RPC_TERMINATE_ORPHAN
#undef KERN_RPC_TERMINATE_ORPHAN
#endif
#ifdef KERN_RPC_CONTINUE_ORPHAN
#undef KERN_RPC_CONTINUE_ORPHAN
#endif
#ifdef KERN_NOT_SUPPORTED
#undef KERN_NOT_SUPPORTED
#endif
#ifdef KERN_NODE_DOWN
#undef KERN_NODE_DOWN
#endif
#ifdef KERN_NOT_WAITING
#undef KERN_NOT_WAITING
#endif
#ifdef KERN_OPERATION_TIMED_OUT
#undef KERN_OPERATION_TIMED_OUT
#endif
#ifdef KERN_CODESIGN_ERROR
#undef KERN_CODESIGN_ERROR
#endif
#ifdef KERN_POLICY_STATIC
#undef KERN_POLICY_STATIC
#endif
#ifdef KERN_INSUFFICIENT_BUFFER_SIZE
#undef KERN_INSUFFICIENT_BUFFER_SIZE
#endif
#ifdef KERN_DENIED
#undef KERN_DENIED
#endif
#endif  // #if AS_UNDEF_VALUES

enum AS_DEFINE_NAME(KERN_RETURN)
{
  AS_DEFINE_NAME(KERN_SUCCESS) = 0,
  AS_DEFINE_NAME(KERN_INVALID_ADDRESS) = 1,
  AS_DEFINE_NAME(KERN_PROTECTION_FAILURE) = 2,
  AS_DEFINE_NAME(KERN_NO_SPACE) = 3,
  AS_DEFINE_NAME(KERN_INVALID_ARGUMENT) = 4,
  AS_DEFINE_NAME(KERN_FAILURE) = 5,
  AS_DEFINE_NAME(KERN_RESOURCE_SHORTAGE) = 6,
  AS_DEFINE_NAME(KERN_NOT_RECEIVER) = 7,
  AS_DEFINE_NAME(KERN_NO_ACCESS) = 8,
  AS_DEFINE_NAME(KERN_MEMORY_FAILURE) = 9,
  AS_DEFINE_NAME(KERN_MEMORY_ERROR) = 10,
  AS_DEFINE_NAME(KERN_ALREADY_IN_SET) = 11,
  AS_DEFINE_NAME(KERN_NOT_IN_SET) = 12,
  AS_DEFINE_NAME(KERN_NAME_EXISTS) = 13,
  AS_DEFINE_NAME(KERN_ABORTED) = 14,
  AS_DEFINE_NAME(KERN_INVALID_NAME) = 15,
  AS_DEFINE_NAME(KERN_INVALID_TASK) = 16,
  AS_DEFINE_NAME(KERN_INVALID_RIGHT) = 17,
  AS_DEFINE_NAME(KERN_INVALID_VALUE) = 18,
  AS_DEFINE_NAME(KERN_UREFS_OVERFLOW) = 19,
  AS_DEFINE_NAME(KERN_INVALID_CAPABILITY) = 20,
  AS_DEFINE_NAME(KERN_RIGHT_EXISTS) = 21,
  AS_DEFINE_NAME(KERN_INVALID_HOST) = 22,
  AS_DEFINE_NAME(KERN_MEMORY_PRESENT) = 23,
  AS_DEFINE_NAME(KERN_MEMORY_DATA_MOVED) = 24,
  AS_DEFINE_NAME(KERN_MEMORY_RESTART_COPY) = 25,
  AS_DEFINE_NAME(KERN_INVALID_PROCESSOR_SET) = 26,
  AS_DEFINE_NAME(KERN_POLICY_LIMIT) = 27,
  AS_DEFINE_NAME(KERN_INVALID_POLICY) = 28,
  AS_DEFINE_NAME(KERN_INVALID_OBJECT) = 29,
  AS_DEFINE_NAME(KERN_ALREADY_WAITING) = 30,
  AS_DEFINE_NAME(KERN_DEFAULT_SET) = 31,
  AS_DEFINE_NAME(KERN_EXCEPTION_PROTECTED) = 32,
  AS_DEFINE_NAME(KERN_INVALID_LEDGER) = 33,
  AS_DEFINE_NAME(KERN_INVALID_MEMORY_CONTROL) = 34,
  AS_DEFINE_NAME(KERN_INVALID_SECURITY) = 35,
  AS_DEFINE_NAME(KERN_NOT_DEPRESSED) = 36,
  AS_DEFINE_NAME(KERN_TERMINATED) = 37,
  AS_DEFINE_NAME(KERN_LOCK_SET_DESTROYED) = 38,
  AS_DEFINE_NAME(KERN_LOCK_UNSTABLE) = 39,
  AS_DEFINE_NAME(KERN_LOCK_OWNED) = 40,
  AS_DEFINE_NAME(KERN_LOCK_OWNED_SELF) = 41,
  AS_DEFINE_NAME(KERN_SEMAPHORE_DESTROYED) = 42,
  AS_DEFINE_NAME(KERN_RPC_SERVER_TERMINATED) = 43,
  AS_DEFINE_NAME(KERN_RPC_TERMINATE_ORPHAN) = 44,
  AS_DEFINE_NAME(KERN_RPC_CONTINUE_ORPHAN) = 45,
  AS_DEFINE_NAME(KERN_NOT_SUPPORTED) = 46,
  AS_DEFINE_NAME(KERN_NODE_DOWN) = 47,
  AS_DEFINE_NAME(KERN_NOT_WAITING) = 48,
  AS_DEFINE_NAME(KERN_OPERATION_TIMED_OUT) = 49,
  AS_DEFINE_NAME(KERN_CODESIGN_ERROR) = 50,
  AS_DEFINE_NAME(KERN_POLICY_STATIC) = 51,
  AS_DEFINE_NAME(KERN_INSUFFICIENT_BUFFER_SIZE) = 52,
  AS_DEFINE_NAME(KERN_DENIED) = 53,
};


AS_NAMESPACE_END()

#endif  // #ifndef __AS_KERN_RETURN__
